// Code generated by protoc-gen-go.
// source: conf.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 获取游戏全局配置数据
type CConfig struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4000" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CConfig) Reset()         { *m = CConfig{} }
func (m *CConfig) String() string { return proto.CompactTextString(m) }
func (*CConfig) ProtoMessage()    {}

const Default_CConfig_Code uint32 = 4000

func (m *CConfig) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CConfig_Code
}

type SConfig struct {
	Code             *uint32        `protobuf:"varint,1,opt,name=code,def=4000" json:"code,omitempty"`
	Room             []*RoomAttrube `protobuf:"bytes,2,rep,name=room" json:"room,omitempty"`
	Sys              *SysConfig     `protobuf:"bytes,4,req,name=sys" json:"sys,omitempty"`
	Error            *uint32        `protobuf:"varint,6,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SConfig) Reset()         { *m = SConfig{} }
func (m *SConfig) String() string { return proto.CompactTextString(m) }
func (*SConfig) ProtoMessage()    {}

const Default_SConfig_Code uint32 = 4000
const Default_SConfig_Error uint32 = 0

func (m *SConfig) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SConfig_Code
}

func (m *SConfig) GetRoom() []*RoomAttrube {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *SConfig) GetSys() *SysConfig {
	if m != nil {
		return m.Sys
	}
	return nil
}

func (m *SConfig) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SConfig_Error
}

// 系统配置
type SysConfig struct {
	Imageserver      *string `protobuf:"bytes,1,req,name=imageserver" json:"imageserver,omitempty"`
	Discardtimeout   *uint32 `protobuf:"varint,2,req,name=discardtimeout" json:"discardtimeout,omitempty"`
	Version          *string `protobuf:"bytes,3,req,name=version" json:"version,omitempty"`
	Feedbackserver   *string `protobuf:"bytes,4,req,name=feedbackserver" json:"feedbackserver,omitempty"`
	Shareaddr        *string `protobuf:"bytes,5,req,name=shareaddr" json:"shareaddr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SysConfig) Reset()         { *m = SysConfig{} }
func (m *SysConfig) String() string { return proto.CompactTextString(m) }
func (*SysConfig) ProtoMessage()    {}

func (m *SysConfig) GetImageserver() string {
	if m != nil && m.Imageserver != nil {
		return *m.Imageserver
	}
	return ""
}

func (m *SysConfig) GetDiscardtimeout() uint32 {
	if m != nil && m.Discardtimeout != nil {
		return *m.Discardtimeout
	}
	return 0
}

func (m *SysConfig) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *SysConfig) GetFeedbackserver() string {
	if m != nil && m.Feedbackserver != nil {
		return *m.Feedbackserver
	}
	return ""
}

func (m *SysConfig) GetShareaddr() string {
	if m != nil && m.Shareaddr != nil {
		return *m.Shareaddr
	}
	return ""
}

func init() {
}
