// Code generated by protoc-gen-go.
// source: error.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Error int32

const (
	Error_UsernameOrPwdError         Error = 13009
	Error_UsernameEmpty              Error = 13010
	Error_RegistError                Error = 13012
	Error_PwdEmpty                   Error = 13011
	Error_PhoneRegisted              Error = 13016
	Error_PhoneNumberError           Error = 13017
	Error_PwdFormatError             Error = 13018
	Error_PhoneNumberEnpty           Error = 13019
	Error_UserDataNotExist           Error = 14001
	Error_WechatLoingFailReAuth      Error = 14003
	Error_GetWechatUserInfoFail      Error = 14004
	Error_HTTP_LOGIN_EXPIRE          Error = 14006
	Error_HTTP_LOGIN_TOKEN_FAIL      Error = 14007
	Error_HTTP_LOGIN_USERDATA_NIL    Error = 14008
	Error_HTTP_LOGIN_USERID_NIL      Error = 14009
	Error_HTTP_LOGIN_USER_NOT_REGIST Error = 14010
	Error_NotInRoomCannotLeave       Error = 20002
	Error_GameStartedCannotLeave     Error = 20001
	Error_NotYourTurn                Error = 20003
	Error_BuyAlready                 Error = 20004
	Error_NoOperate                  Error = 20005
	Error_NoStarted                  Error = 20006
	Error_GameRoundIllegal           Error = 20008
	Error_GameMaiziIllegal           Error = 20009
	Error_CardValueZero              Error = 20007
	Error_NotInRoom                  Error = 20018
	Error_NotEnoughCoin              Error = 20019
	Error_StartedNotKick             Error = 20023
	Error_CreateRoomFail             Error = 30012
	Error_RoomNotExist               Error = 30016
	Error_RoomFull                   Error = 30018
	Error_NotInPrivateRoom           Error = 30019
	Error_RunningNotVote             Error = 30032
	Error_VotingCantLaunchVote       Error = 30033
	Error_NotVoteTime                Error = 30034
	Error_NameTooLong                Error = 40002
	Error_SexValueRangeout           Error = 40004
	Error_FeedfackError              Error = 40005
	Error_NotEnough_ROOM_CARD        Error = 40007
	Error_NoticeListEnpty            Error = 40008
	Error_DataOutOfRange             Error = 40009
	Error_IpayOrderFail              Error = 62001
	Error_PostboxEmpty               Error = 69001
	Error_PostNotExist               Error = 69002
	Error_AppendixNotExist           Error = 69003
	Error_PrivateRecordEmpty         Error = 68004
)

var Error_name = map[int32]string{
	13009: "UsernameOrPwdError",
	13010: "UsernameEmpty",
	13012: "RegistError",
	13011: "PwdEmpty",
	13016: "PhoneRegisted",
	13017: "PhoneNumberError",
	13018: "PwdFormatError",
	13019: "PhoneNumberEnpty",
	14001: "UserDataNotExist",
	14003: "WechatLoingFailReAuth",
	14004: "GetWechatUserInfoFail",
	14006: "HTTP_LOGIN_EXPIRE",
	14007: "HTTP_LOGIN_TOKEN_FAIL",
	14008: "HTTP_LOGIN_USERDATA_NIL",
	14009: "HTTP_LOGIN_USERID_NIL",
	14010: "HTTP_LOGIN_USER_NOT_REGIST",
	20002: "NotInRoomCannotLeave",
	20001: "GameStartedCannotLeave",
	20003: "NotYourTurn",
	20004: "BuyAlready",
	20005: "NoOperate",
	20006: "NoStarted",
	20008: "GameRoundIllegal",
	20009: "GameMaiziIllegal",
	20007: "CardValueZero",
	20018: "NotInRoom",
	20019: "NotEnoughCoin",
	20023: "StartedNotKick",
	30012: "CreateRoomFail",
	30016: "RoomNotExist",
	30018: "RoomFull",
	30019: "NotInPrivateRoom",
	30032: "RunningNotVote",
	30033: "VotingCantLaunchVote",
	30034: "NotVoteTime",
	40002: "NameTooLong",
	40004: "SexValueRangeout",
	40005: "FeedfackError",
	40007: "NotEnough_ROOM_CARD",
	40008: "NoticeListEnpty",
	40009: "DataOutOfRange",
	62001: "IpayOrderFail",
	69001: "PostboxEmpty",
	69002: "PostNotExist",
	69003: "AppendixNotExist",
	68004: "PrivateRecordEmpty",
}
var Error_value = map[string]int32{
	"UsernameOrPwdError":         13009,
	"UsernameEmpty":              13010,
	"RegistError":                13012,
	"PwdEmpty":                   13011,
	"PhoneRegisted":              13016,
	"PhoneNumberError":           13017,
	"PwdFormatError":             13018,
	"PhoneNumberEnpty":           13019,
	"UserDataNotExist":           14001,
	"WechatLoingFailReAuth":      14003,
	"GetWechatUserInfoFail":      14004,
	"HTTP_LOGIN_EXPIRE":          14006,
	"HTTP_LOGIN_TOKEN_FAIL":      14007,
	"HTTP_LOGIN_USERDATA_NIL":    14008,
	"HTTP_LOGIN_USERID_NIL":      14009,
	"HTTP_LOGIN_USER_NOT_REGIST": 14010,
	"NotInRoomCannotLeave":       20002,
	"GameStartedCannotLeave":     20001,
	"NotYourTurn":                20003,
	"BuyAlready":                 20004,
	"NoOperate":                  20005,
	"NoStarted":                  20006,
	"GameRoundIllegal":           20008,
	"GameMaiziIllegal":           20009,
	"CardValueZero":              20007,
	"NotInRoom":                  20018,
	"NotEnoughCoin":              20019,
	"StartedNotKick":             20023,
	"CreateRoomFail":             30012,
	"RoomNotExist":               30016,
	"RoomFull":                   30018,
	"NotInPrivateRoom":           30019,
	"RunningNotVote":             30032,
	"VotingCantLaunchVote":       30033,
	"NotVoteTime":                30034,
	"NameTooLong":                40002,
	"SexValueRangeout":           40004,
	"FeedfackError":              40005,
	"NotEnough_ROOM_CARD":        40007,
	"NoticeListEnpty":            40008,
	"DataOutOfRange":             40009,
	"IpayOrderFail":              62001,
	"PostboxEmpty":               69001,
	"PostNotExist":               69002,
	"AppendixNotExist":           69003,
	"PrivateRecordEmpty":         68004,
}

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}
func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}
func (x *Error) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Error_value, data, "Error")
	if err != nil {
		return err
	}
	*x = Error(value)
	return nil
}

func init() {
	proto.RegisterEnum("protocol.Error", Error_name, Error_value)
}
