// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// http登陆获取登录令牌后登录游戏服
type CHttpLogin struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1026" json:"code,omitempty"`
	Userid           *string `protobuf:"bytes,2,req,name=userid" json:"userid,omitempty"`
	Timestamp        *uint32 `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	Createtime       *uint32 `protobuf:"varint,4,req,name=createtime" json:"createtime,omitempty"`
	Token            *string `protobuf:"bytes,5,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CHttpLogin) Reset()         { *m = CHttpLogin{} }
func (m *CHttpLogin) String() string { return proto.CompactTextString(m) }
func (*CHttpLogin) ProtoMessage()    {}

const Default_CHttpLogin_Code uint32 = 1026

func (m *CHttpLogin) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CHttpLogin_Code
}

func (m *CHttpLogin) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *CHttpLogin) GetTimestamp() uint32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *CHttpLogin) GetCreatetime() uint32 {
	if m != nil && m.Createtime != nil {
		return *m.Createtime
	}
	return 0
}

func (m *CHttpLogin) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type SHttpLogin struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1026" json:"code,omitempty"`
	Userid           *string `protobuf:"bytes,3,req,name=userid" json:"userid,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SHttpLogin) Reset()         { *m = SHttpLogin{} }
func (m *SHttpLogin) String() string { return proto.CompactTextString(m) }
func (*SHttpLogin) ProtoMessage()    {}

const Default_SHttpLogin_Code uint32 = 1026
const Default_SHttpLogin_Error uint32 = 0

func (m *SHttpLogin) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SHttpLogin_Code
}

func (m *SHttpLogin) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *SHttpLogin) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SHttpLogin_Error
}

// 登陆
type CLogin struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1000" json:"code,omitempty"`
	Userid           *string `protobuf:"bytes,2,opt,name=userid" json:"userid,omitempty"`
	Phone            *string `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
	Password         *string `protobuf:"bytes,4,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CLogin) Reset()         { *m = CLogin{} }
func (m *CLogin) String() string { return proto.CompactTextString(m) }
func (*CLogin) ProtoMessage()    {}

const Default_CLogin_Code uint32 = 1000

func (m *CLogin) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CLogin_Code
}

func (m *CLogin) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *CLogin) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *CLogin) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type SLogin struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1000" json:"code,omitempty"`
	Userid           *string `protobuf:"bytes,2,req,name=userid" json:"userid,omitempty"`
	Unixtime         *uint32 `protobuf:"varint,3,req,name=unixtime" json:"unixtime,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SLogin) Reset()         { *m = SLogin{} }
func (m *SLogin) String() string { return proto.CompactTextString(m) }
func (*SLogin) ProtoMessage()    {}

const Default_SLogin_Code uint32 = 1000
const Default_SLogin_Error uint32 = 0

func (m *SLogin) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SLogin_Code
}

func (m *SLogin) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *SLogin) GetUnixtime() uint32 {
	if m != nil && m.Unixtime != nil {
		return *m.Unixtime
	}
	return 0
}

func (m *SLogin) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SLogin_Error
}

// 咪咕登陆
type CMiguLogin struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1001" json:"code,omitempty"`
	Sessionkey       *string `protobuf:"bytes,2,opt,name=sessionkey" json:"sessionkey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMiguLogin) Reset()         { *m = CMiguLogin{} }
func (m *CMiguLogin) String() string { return proto.CompactTextString(m) }
func (*CMiguLogin) ProtoMessage()    {}

const Default_CMiguLogin_Code uint32 = 1001

func (m *CMiguLogin) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CMiguLogin_Code
}

func (m *CMiguLogin) GetSessionkey() string {
	if m != nil && m.Sessionkey != nil {
		return *m.Sessionkey
	}
	return ""
}

type SMiguLogin struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1001" json:"code,omitempty"`
	Userid           *string `protobuf:"bytes,2,req,name=userid" json:"userid,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SMiguLogin) Reset()         { *m = SMiguLogin{} }
func (m *SMiguLogin) String() string { return proto.CompactTextString(m) }
func (*SMiguLogin) ProtoMessage()    {}

const Default_SMiguLogin_Code uint32 = 1001
const Default_SMiguLogin_Error uint32 = 0

func (m *SMiguLogin) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SMiguLogin_Code
}

func (m *SMiguLogin) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *SMiguLogin) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SMiguLogin_Error
}

// 账户重复登录协议
type ReLogin struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1010" json:"code,omitempty"`
	Error            *uint32 `protobuf:"varint,2,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReLogin) Reset()         { *m = ReLogin{} }
func (m *ReLogin) String() string { return proto.CompactTextString(m) }
func (*ReLogin) ProtoMessage()    {}

const Default_ReLogin_Code uint32 = 1010
const Default_ReLogin_Error uint32 = 0

func (m *ReLogin) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_ReLogin_Code
}

func (m *ReLogin) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_ReLogin_Error
}

type CRegist struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1022" json:"code,omitempty"`
	Nickname         *string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Phone            *string `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
	Pwd              *string `protobuf:"bytes,4,req,name=pwd" json:"pwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CRegist) Reset()         { *m = CRegist{} }
func (m *CRegist) String() string { return proto.CompactTextString(m) }
func (*CRegist) ProtoMessage()    {}

const Default_CRegist_Code uint32 = 1022

func (m *CRegist) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CRegist_Code
}

func (m *CRegist) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *CRegist) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *CRegist) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

type SRegist struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1022" json:"code,omitempty"`
	Userid           *string `protobuf:"bytes,2,opt,name=userid" json:"userid,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SRegist) Reset()         { *m = SRegist{} }
func (m *SRegist) String() string { return proto.CompactTextString(m) }
func (*SRegist) ProtoMessage()    {}

const Default_SRegist_Code uint32 = 1022
const Default_SRegist_Error uint32 = 0

func (m *SRegist) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SRegist_Code
}

func (m *SRegist) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *SRegist) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SRegist_Error
}

// 修改密码
type CSetPasswd struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1023" json:"code,omitempty"`
	Pwd              *string `protobuf:"bytes,2,req,name=pwd" json:"pwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CSetPasswd) Reset()         { *m = CSetPasswd{} }
func (m *CSetPasswd) String() string { return proto.CompactTextString(m) }
func (*CSetPasswd) ProtoMessage()    {}

const Default_CSetPasswd_Code uint32 = 1023

func (m *CSetPasswd) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CSetPasswd_Code
}

func (m *CSetPasswd) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

type SSetPasswd struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1023" json:"code,omitempty"`
	Result           *uint32 `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SSetPasswd) Reset()         { *m = SSetPasswd{} }
func (m *SSetPasswd) String() string { return proto.CompactTextString(m) }
func (*SSetPasswd) ProtoMessage()    {}

const Default_SSetPasswd_Code uint32 = 1023
const Default_SSetPasswd_Error uint32 = 0

func (m *SSetPasswd) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SSetPasswd_Code
}

func (m *SSetPasswd) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SSetPasswd) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SSetPasswd_Error
}

// 服务器主动断开网络
type Sdisconnection struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1032" json:"code,omitempty"`
	Error            *uint32 `protobuf:"varint,2,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Sdisconnection) Reset()         { *m = Sdisconnection{} }
func (m *Sdisconnection) String() string { return proto.CompactTextString(m) }
func (*Sdisconnection) ProtoMessage()    {}

const Default_Sdisconnection_Code uint32 = 1032
const Default_Sdisconnection_Error uint32 = 0

func (m *Sdisconnection) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_Sdisconnection_Code
}

func (m *Sdisconnection) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_Sdisconnection_Error
}

// 微信登录登陆
type CWechatLogin struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1024" json:"code,omitempty"`
	Appid            *string `protobuf:"bytes,2,req,name=appid" json:"appid,omitempty"`
	Secret           *string `protobuf:"bytes,3,req,name=secret" json:"secret,omitempty"`
	CodeId           *string `protobuf:"bytes,4,req,name=code_id" json:"code_id,omitempty"`
	GrantType        *string `protobuf:"bytes,5,req,name=grant_type" json:"grant_type,omitempty"`
	Token            *string `protobuf:"bytes,6,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CWechatLogin) Reset()         { *m = CWechatLogin{} }
func (m *CWechatLogin) String() string { return proto.CompactTextString(m) }
func (*CWechatLogin) ProtoMessage()    {}

const Default_CWechatLogin_Code uint32 = 1024

func (m *CWechatLogin) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CWechatLogin_Code
}

func (m *CWechatLogin) GetAppid() string {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return ""
}

func (m *CWechatLogin) GetSecret() string {
	if m != nil && m.Secret != nil {
		return *m.Secret
	}
	return ""
}

func (m *CWechatLogin) GetCodeId() string {
	if m != nil && m.CodeId != nil {
		return *m.CodeId
	}
	return ""
}

func (m *CWechatLogin) GetGrantType() string {
	if m != nil && m.GrantType != nil {
		return *m.GrantType
	}
	return ""
}

func (m *CWechatLogin) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type SWechatLogin struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1024" json:"code,omitempty"`
	Userid           *string `protobuf:"bytes,2,req,name=userid" json:"userid,omitempty"`
	Token            *string `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SWechatLogin) Reset()         { *m = SWechatLogin{} }
func (m *SWechatLogin) String() string { return proto.CompactTextString(m) }
func (*SWechatLogin) ProtoMessage()    {}

const Default_SWechatLogin_Code uint32 = 1024
const Default_SWechatLogin_Error uint32 = 0

func (m *SWechatLogin) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SWechatLogin_Code
}

func (m *SWechatLogin) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *SWechatLogin) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *SWechatLogin) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SWechatLogin_Error
}

func init() {
}
