// Code generated by protoc-gen-go.
// source: postbox.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type CPost struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7701" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPost) Reset()         { *m = CPost{} }
func (m *CPost) String() string { return proto.CompactTextString(m) }
func (*CPost) ProtoMessage()    {}

const Default_CPost_Code uint32 = 7701

func (m *CPost) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CPost_Code
}

type SPost struct {
	Code             *uint32        `protobuf:"varint,1,opt,name=code,def=7701" json:"code,omitempty"`
	Data             []*PostBoxData `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
	Error            *uint32        `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SPost) Reset()         { *m = SPost{} }
func (m *SPost) String() string { return proto.CompactTextString(m) }
func (*SPost) ProtoMessage()    {}

const Default_SPost_Code uint32 = 7701
const Default_SPost_Error uint32 = 0

func (m *SPost) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPost_Code
}

func (m *SPost) GetData() []*PostBoxData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SPost) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SPost_Error
}

type CDelPost struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7702" json:"code,omitempty"`
	Postid           *uint32 `protobuf:"varint,2,req,name=postid" json:"postid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDelPost) Reset()         { *m = CDelPost{} }
func (m *CDelPost) String() string { return proto.CompactTextString(m) }
func (*CDelPost) ProtoMessage()    {}

const Default_CDelPost_Code uint32 = 7702

func (m *CDelPost) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CDelPost_Code
}

func (m *CDelPost) GetPostid() uint32 {
	if m != nil && m.Postid != nil {
		return *m.Postid
	}
	return 0
}

type SDelPost struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7702" json:"code,omitempty"`
	Postid           *uint32 `protobuf:"varint,2,req,name=postid" json:"postid,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SDelPost) Reset()         { *m = SDelPost{} }
func (m *SDelPost) String() string { return proto.CompactTextString(m) }
func (*SDelPost) ProtoMessage()    {}

const Default_SDelPost_Code uint32 = 7702
const Default_SDelPost_Error uint32 = 0

func (m *SDelPost) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SDelPost_Code
}

func (m *SDelPost) GetPostid() uint32 {
	if m != nil && m.Postid != nil {
		return *m.Postid
	}
	return 0
}

func (m *SDelPost) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SDelPost_Error
}

type CDelReadPost struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7703" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDelReadPost) Reset()         { *m = CDelReadPost{} }
func (m *CDelReadPost) String() string { return proto.CompactTextString(m) }
func (*CDelReadPost) ProtoMessage()    {}

const Default_CDelReadPost_Code uint32 = 7703

func (m *CDelReadPost) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CDelReadPost_Code
}

type SDelReadPost struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7703" json:"code,omitempty"`
	Error            *uint32 `protobuf:"varint,2,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SDelReadPost) Reset()         { *m = SDelReadPost{} }
func (m *SDelReadPost) String() string { return proto.CompactTextString(m) }
func (*SDelReadPost) ProtoMessage()    {}

const Default_SDelReadPost_Code uint32 = 7703
const Default_SDelReadPost_Error uint32 = 0

func (m *SDelReadPost) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SDelReadPost_Code
}

func (m *SDelReadPost) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SDelReadPost_Error
}

type CDelAllPost struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7704" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDelAllPost) Reset()         { *m = CDelAllPost{} }
func (m *CDelAllPost) String() string { return proto.CompactTextString(m) }
func (*CDelAllPost) ProtoMessage()    {}

const Default_CDelAllPost_Code uint32 = 7704

func (m *CDelAllPost) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CDelAllPost_Code
}

type SDelAllPost struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7704" json:"code,omitempty"`
	Error            *uint32 `protobuf:"varint,2,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SDelAllPost) Reset()         { *m = SDelAllPost{} }
func (m *SDelAllPost) String() string { return proto.CompactTextString(m) }
func (*SDelAllPost) ProtoMessage()    {}

const Default_SDelAllPost_Code uint32 = 7704
const Default_SDelAllPost_Error uint32 = 0

func (m *SDelAllPost) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SDelAllPost_Code
}

func (m *SDelAllPost) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SDelAllPost_Error
}

type COpenAppendix struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7705" json:"code,omitempty"`
	Postid           *uint32 `protobuf:"varint,2,req,name=postid" json:"postid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *COpenAppendix) Reset()         { *m = COpenAppendix{} }
func (m *COpenAppendix) String() string { return proto.CompactTextString(m) }
func (*COpenAppendix) ProtoMessage()    {}

const Default_COpenAppendix_Code uint32 = 7705

func (m *COpenAppendix) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_COpenAppendix_Code
}

func (m *COpenAppendix) GetPostid() uint32 {
	if m != nil && m.Postid != nil {
		return *m.Postid
	}
	return 0
}

type SOpenAppendix struct {
	Code             *uint32           `protobuf:"varint,1,opt,name=code,def=7705" json:"code,omitempty"`
	Data             *PostAppendixData `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	Error            *uint32           `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *SOpenAppendix) Reset()         { *m = SOpenAppendix{} }
func (m *SOpenAppendix) String() string { return proto.CompactTextString(m) }
func (*SOpenAppendix) ProtoMessage()    {}

const Default_SOpenAppendix_Code uint32 = 7705
const Default_SOpenAppendix_Error uint32 = 0

func (m *SOpenAppendix) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SOpenAppendix_Code
}

func (m *SOpenAppendix) GetData() *PostAppendixData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SOpenAppendix) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SOpenAppendix_Error
}

type CReadPost struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7706" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CReadPost) Reset()         { *m = CReadPost{} }
func (m *CReadPost) String() string { return proto.CompactTextString(m) }
func (*CReadPost) ProtoMessage()    {}

const Default_CReadPost_Code uint32 = 7706

func (m *CReadPost) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CReadPost_Code
}

func (m *CReadPost) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type SReadPost struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7706" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SReadPost) Reset()         { *m = SReadPost{} }
func (m *SReadPost) String() string { return proto.CompactTextString(m) }
func (*SReadPost) ProtoMessage()    {}

const Default_SReadPost_Code uint32 = 7706
const Default_SReadPost_Error uint32 = 0

func (m *SReadPost) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SReadPost_Code
}

func (m *SReadPost) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SReadPost) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SReadPost_Error
}

func init() {
}
