// Code generated by protoc-gen-go.
// source: room.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 匹配并进入房间
type CComein struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2000" json:"code,omitempty"`
	Rtype            *uint32 `protobuf:"varint,2,req,name=rtype" json:"rtype,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CComein) Reset()         { *m = CComein{} }
func (m *CComein) String() string { return proto.CompactTextString(m) }
func (*CComein) ProtoMessage()    {}

const Default_CComein_Code uint32 = 2000

func (m *CComein) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CComein_Code
}

func (m *CComein) GetRtype() uint32 {
	if m != nil && m.Rtype != nil {
		return *m.Rtype
	}
	return 0
}

// 玩家进入房间，如果成功，会广播房间其他玩家
type SComein struct {
	Code             *uint32      `protobuf:"varint,1,opt,name=code,def=2000" json:"code,omitempty"`
	Position         *uint32      `protobuf:"varint,2,req" json:"Position,omitempty"`
	Room             *ProtoRoom   `protobuf:"bytes,3,req,name=room" json:"room,omitempty"`
	Userinfo         []*ProtoUser `protobuf:"bytes,4,rep,name=userinfo" json:"userinfo,omitempty"`
	Rtype            *uint32      `protobuf:"varint,5,req,name=rtype" json:"rtype,omitempty"`
	Error            *uint32      `protobuf:"varint,6,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SComein) Reset()         { *m = SComein{} }
func (m *SComein) String() string { return proto.CompactTextString(m) }
func (*SComein) ProtoMessage()    {}

const Default_SComein_Code uint32 = 2000
const Default_SComein_Error uint32 = 0

func (m *SComein) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SComein_Code
}

func (m *SComein) GetPosition() uint32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *SComein) GetRoom() *ProtoRoom {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *SComein) GetUserinfo() []*ProtoUser {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

func (m *SComein) GetRtype() uint32 {
	if m != nil && m.Rtype != nil {
		return *m.Rtype
	}
	return 0
}

func (m *SComein) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SComein_Error
}

// 其他玩家进入房间
type SOtherComein struct {
	Code             *uint32    `protobuf:"varint,1,opt,name=code,def=2001" json:"code,omitempty"`
	Userinfo         *ProtoUser `protobuf:"bytes,2,req,name=userinfo" json:"userinfo,omitempty"`
	Error            *uint32    `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *SOtherComein) Reset()         { *m = SOtherComein{} }
func (m *SOtherComein) String() string { return proto.CompactTextString(m) }
func (*SOtherComein) ProtoMessage()    {}

const Default_SOtherComein_Code uint32 = 2001
const Default_SOtherComein_Error uint32 = 0

func (m *SOtherComein) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SOtherComein_Code
}

func (m *SOtherComein) GetUserinfo() *ProtoUser {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

func (m *SOtherComein) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SOtherComein_Error
}

// 打庄
type SZhuang struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2002" json:"code,omitempty"`
	Zhuang           *uint32 `protobuf:"varint,2,req,name=zhuang" json:"zhuang,omitempty"`
	Lian             *uint32 `protobuf:"varint,3,req,name=lian" json:"lian,omitempty"`
	Watchseat        *uint32 `protobuf:"varint,4,req,name=watchseat" json:"watchseat,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SZhuang) Reset()         { *m = SZhuang{} }
func (m *SZhuang) String() string { return proto.CompactTextString(m) }
func (*SZhuang) ProtoMessage()    {}

const Default_SZhuang_Code uint32 = 2002
const Default_SZhuang_Error uint32 = 0

func (m *SZhuang) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SZhuang_Code
}

func (m *SZhuang) GetZhuang() uint32 {
	if m != nil && m.Zhuang != nil {
		return *m.Zhuang
	}
	return 0
}

func (m *SZhuang) GetLian() uint32 {
	if m != nil && m.Lian != nil {
		return *m.Lian
	}
	return 0
}

func (m *SZhuang) GetWatchseat() uint32 {
	if m != nil && m.Watchseat != nil {
		return *m.Watchseat
	}
	return 0
}

func (m *SZhuang) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SZhuang_Error
}

// 进入指定房间 响应2000
type CComeinRoomid struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2003" json:"code,omitempty"`
	Roomid           *uint32 `protobuf:"varint,2,req,name=roomid" json:"roomid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CComeinRoomid) Reset()         { *m = CComeinRoomid{} }
func (m *CComeinRoomid) String() string { return proto.CompactTextString(m) }
func (*CComeinRoomid) ProtoMessage()    {}

const Default_CComeinRoomid_Code uint32 = 2003

func (m *CComeinRoomid) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CComeinRoomid_Code
}

func (m *CComeinRoomid) GetRoomid() uint32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

// 等待玩家打骰子
type SWaitBroken struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2008" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SWaitBroken) Reset()         { *m = SWaitBroken{} }
func (m *SWaitBroken) String() string { return proto.CompactTextString(m) }
func (*SWaitBroken) ProtoMessage()    {}

const Default_SWaitBroken_Code uint32 = 2008

func (m *SWaitBroken) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SWaitBroken_Code
}

// 玩家打骰子
type CBroken struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2007" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CBroken) Reset()         { *m = CBroken{} }
func (m *CBroken) String() string { return proto.CompactTextString(m) }
func (*CBroken) ProtoMessage()    {}

const Default_CBroken_Code uint32 = 2007

func (m *CBroken) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CBroken_Code
}

// 非广播接口(骰子数据合并到发牌广播数据里）
type SBroken struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2007" json:"code,omitempty"`
	Error            *uint32 `protobuf:"varint,2,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SBroken) Reset()         { *m = SBroken{} }
func (m *SBroken) String() string { return proto.CompactTextString(m) }
func (*SBroken) ProtoMessage()    {}

const Default_SBroken_Code uint32 = 2007
const Default_SBroken_Error uint32 = 0

func (m *SBroken) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SBroken_Code
}

func (m *SBroken) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SBroken_Error
}

// 庄家发牌,包含两个骰子数字
type SZhuangDeal struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2037" json:"code,omitempty"`
	Dice             *uint32 `protobuf:"varint,2,req,name=dice" json:"dice,omitempty"`
	Cards            []byte  `protobuf:"bytes,3,req,name=cards" json:"cards,omitempty"`
	Value            *int64  `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
	LuckyCard        *uint32 `protobuf:"varint,5,opt,name=luckyCard" json:"luckyCard,omitempty"`
	Error            *uint32 `protobuf:"varint,6,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SZhuangDeal) Reset()         { *m = SZhuangDeal{} }
func (m *SZhuangDeal) String() string { return proto.CompactTextString(m) }
func (*SZhuangDeal) ProtoMessage()    {}

const Default_SZhuangDeal_Code uint32 = 2037
const Default_SZhuangDeal_Error uint32 = 0

func (m *SZhuangDeal) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SZhuangDeal_Code
}

func (m *SZhuangDeal) GetDice() uint32 {
	if m != nil && m.Dice != nil {
		return *m.Dice
	}
	return 0
}

func (m *SZhuangDeal) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *SZhuangDeal) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SZhuangDeal) GetLuckyCard() uint32 {
	if m != nil && m.LuckyCard != nil {
		return *m.LuckyCard
	}
	return 0
}

func (m *SZhuangDeal) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SZhuangDeal_Error
}

// 发牌,包含两个骰子数字
type SDeal struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2004" json:"code,omitempty"`
	Dice             *uint32 `protobuf:"varint,2,req,name=dice" json:"dice,omitempty"`
	Cards            []byte  `protobuf:"bytes,3,req,name=cards" json:"cards,omitempty"`
	Value            *int64  `protobuf:"varint,4,req,name=value" json:"value,omitempty"`
	LuckyCard        *uint32 `protobuf:"varint,5,opt,name=luckyCard" json:"luckyCard,omitempty"`
	Error            *uint32 `protobuf:"varint,6,req,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SDeal) Reset()         { *m = SDeal{} }
func (m *SDeal) String() string { return proto.CompactTextString(m) }
func (*SDeal) ProtoMessage()    {}

const Default_SDeal_Code uint32 = 2004
const Default_SDeal_Error uint32 = 0

func (m *SDeal) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SDeal_Code
}

func (m *SDeal) GetDice() uint32 {
	if m != nil && m.Dice != nil {
		return *m.Dice
	}
	return 0
}

func (m *SDeal) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *SDeal) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SDeal) GetLuckyCard() uint32 {
	if m != nil && m.LuckyCard != nil {
		return *m.LuckyCard
	}
	return 0
}

func (m *SDeal) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SDeal_Error
}

// 抓牌
// 明杠  MING_KONG uint32 = 2 << 1
// 暗杠	AN_KONG   uint32 = 2 << 2
// 补杠 	BU_KONG   uint32 = 2 << 3
type SDraw struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2005" json:"code,omitempty"`
	Card             *uint32 `protobuf:"varint,2,opt,name=card" json:"card,omitempty"`
	Value            *int64  `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
	Kong             *uint32 `protobuf:"varint,4,opt,name=kong" json:"kong,omitempty"`
	Cards            []byte  `protobuf:"bytes,5,req,name=cards" json:"cards,omitempty"`
	Remainder        *uint32 `protobuf:"varint,6,opt,name=remainder" json:"remainder,omitempty"`
	Error            *uint32 `protobuf:"varint,7,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SDraw) Reset()         { *m = SDraw{} }
func (m *SDraw) String() string { return proto.CompactTextString(m) }
func (*SDraw) ProtoMessage()    {}

const Default_SDraw_Code uint32 = 2005
const Default_SDraw_Error uint32 = 0

func (m *SDraw) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SDraw_Code
}

func (m *SDraw) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *SDraw) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SDraw) GetKong() uint32 {
	if m != nil && m.Kong != nil {
		return *m.Kong
	}
	return 0
}

func (m *SDraw) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *SDraw) GetRemainder() uint32 {
	if m != nil && m.Remainder != nil {
		return *m.Remainder
	}
	return 0
}

func (m *SDraw) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SDraw_Error
}

// 出牌
type CDiscard struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2006" json:"code,omitempty"`
	Value            *int64  `protobuf:"varint,2,req,name=value" json:"value,omitempty"`
	Card             *uint32 `protobuf:"varint,3,req,name=card" json:"card,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDiscard) Reset()         { *m = CDiscard{} }
func (m *CDiscard) String() string { return proto.CompactTextString(m) }
func (*CDiscard) ProtoMessage()    {}

const Default_CDiscard_Code uint32 = 2006

func (m *CDiscard) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CDiscard_Code
}

func (m *CDiscard) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *CDiscard) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

// 其他玩家摸牌
type SOtherDraw struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2016" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Kong             *uint32 `protobuf:"varint,3,opt,name=kong" json:"kong,omitempty"`
	Remainder        *uint32 `protobuf:"varint,4,opt,name=remainder" json:"remainder,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SOtherDraw) Reset()         { *m = SOtherDraw{} }
func (m *SOtherDraw) String() string { return proto.CompactTextString(m) }
func (*SOtherDraw) ProtoMessage()    {}

const Default_SOtherDraw_Code uint32 = 2016
const Default_SOtherDraw_Error uint32 = 0

func (m *SOtherDraw) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SOtherDraw_Code
}

func (m *SOtherDraw) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SOtherDraw) GetKong() uint32 {
	if m != nil && m.Kong != nil {
		return *m.Kong
	}
	return 0
}

func (m *SOtherDraw) GetRemainder() uint32 {
	if m != nil && m.Remainder != nil {
		return *m.Remainder
	}
	return 0
}

func (m *SOtherDraw) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SOtherDraw_Error
}

// 玩家出牌广播
type SDiscard struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2006" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Card             *uint32 `protobuf:"varint,3,req,name=card" json:"card,omitempty"`
	Value            *int64  `protobuf:"varint,4,req,name=value" json:"value,omitempty"`
	Ting             *uint32 `protobuf:"varint,5,req,name=ting" json:"ting,omitempty"`
	Error            *uint32 `protobuf:"varint,6,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SDiscard) Reset()         { *m = SDiscard{} }
func (m *SDiscard) String() string { return proto.CompactTextString(m) }
func (*SDiscard) ProtoMessage()    {}

const Default_SDiscard_Code uint32 = 2006
const Default_SDiscard_Error uint32 = 0

func (m *SDiscard) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SDiscard_Code
}

func (m *SDiscard) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SDiscard) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *SDiscard) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SDiscard) GetTing() uint32 {
	if m != nil && m.Ting != nil {
		return *m.Ting
	}
	return 0
}

func (m *SDiscard) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SDiscard_Error
}

// 玩家碰杠操作
// 碰	PENG      uint32 = 2 << 0
// 明杠	MING_KONG uint32 = 2 << 1
// 暗杠	AN_KONG   uint32 = 2 << 2
// 补杠 	BU_KONG   uint32 = 2 << 3
type COperate struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2012" json:"code,omitempty"`
	Card             *uint32 `protobuf:"varint,2,req,name=card" json:"card,omitempty"`
	Value            *int64  `protobuf:"varint,3,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *COperate) Reset()         { *m = COperate{} }
func (m *COperate) String() string { return proto.CompactTextString(m) }
func (*COperate) ProtoMessage()    {}

const Default_COperate_Code uint32 = 2012

func (m *COperate) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_COperate_Code
}

func (m *COperate) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *COperate) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

// 碰杠广播 ,胡牌不在这个接口返回
type SOperate struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2012" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Beseat           *uint32 `protobuf:"varint,3,req,name=beseat" json:"beseat,omitempty"`
	Card             *uint32 `protobuf:"varint,4,req,name=card" json:"card,omitempty"`
	Dutycard         *uint32 `protobuf:"varint,5,req,name=dutycard" json:"dutycard,omitempty"`
	Value            *int64  `protobuf:"varint,6,req,name=value" json:"value,omitempty"`
	Discontinue      *int64  `protobuf:"varint,7,req,name=discontinue" json:"discontinue,omitempty"`
	Error            *uint32 `protobuf:"varint,8,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SOperate) Reset()         { *m = SOperate{} }
func (m *SOperate) String() string { return proto.CompactTextString(m) }
func (*SOperate) ProtoMessage()    {}

const Default_SOperate_Code uint32 = 2012
const Default_SOperate_Error uint32 = 0

func (m *SOperate) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SOperate_Code
}

func (m *SOperate) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SOperate) GetBeseat() uint32 {
	if m != nil && m.Beseat != nil {
		return *m.Beseat
	}
	return 0
}

func (m *SOperate) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *SOperate) GetDutycard() uint32 {
	if m != nil && m.Dutycard != nil {
		return *m.Dutycard
	}
	return 0
}

func (m *SOperate) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SOperate) GetDiscontinue() int64 {
	if m != nil && m.Discontinue != nil {
		return *m.Discontinue
	}
	return 0
}

func (m *SOperate) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SOperate_Error
}

// 处理前面有玩家胡牌优先操作,如果该玩家跳过胡牌,此协议向有碰和明杠的玩家主动发送
type SPengKong struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2013" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Card             *uint32 `protobuf:"varint,3,req,name=card" json:"card,omitempty"`
	Value            *int64  `protobuf:"varint,4,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SPengKong) Reset()         { *m = SPengKong{} }
func (m *SPengKong) String() string { return proto.CompactTextString(m) }
func (*SPengKong) ProtoMessage()    {}

const Default_SPengKong_Code uint32 = 2013

func (m *SPengKong) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPengKong_Code
}

func (m *SPengKong) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SPengKong) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *SPengKong) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

// 玩家胡牌，如果成功，会广播房间其他玩家
type SHu struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2030" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	TargetSeat       *uint32 `protobuf:"varint,3,req,name=targetSeat" json:"targetSeat,omitempty"`
	Card             *uint32 `protobuf:"varint,4,req,name=card" json:"card,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SHu) Reset()         { *m = SHu{} }
func (m *SHu) String() string { return proto.CompactTextString(m) }
func (*SHu) ProtoMessage()    {}

const Default_SHu_Code uint32 = 2030
const Default_SHu_Error uint32 = 0

func (m *SHu) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SHu_Code
}

func (m *SHu) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SHu) GetTargetSeat() uint32 {
	if m != nil && m.TargetSeat != nil {
		return *m.TargetSeat
	}
	return 0
}

func (m *SHu) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *SHu) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SHu_Error
}

// 胡牌独立接口,胡牌根碰杠接口分离，主要时胡牌算法比较复杂，单独方便处理, 代码量少
type CHu struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2030" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CHu) Reset()         { *m = CHu{} }
func (m *CHu) String() string { return proto.CompactTextString(m) }
func (*CHu) ProtoMessage()    {}

const Default_CHu_Code uint32 = 2030

func (m *CHu) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CHu_Code
}

// 结算广播接口，游戏结束
type SGameover struct {
	Code             *uint32       `protobuf:"varint,1,opt,name=code,def=2028" json:"code,omitempty"`
	HuType           *uint32       `protobuf:"varint,2,req,name=huType" json:"huType,omitempty"`
	PaoSeat          *uint32       `protobuf:"varint,3,req,name=paoSeat" json:"paoSeat,omitempty"`
	Data             []*ProtoCount `protobuf:"bytes,4,rep,name=data" json:"data,omitempty"`
	LianCount        *uint32       `protobuf:"varint,5,req,name=lianCount" json:"lianCount,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SGameover) Reset()         { *m = SGameover{} }
func (m *SGameover) String() string { return proto.CompactTextString(m) }
func (*SGameover) ProtoMessage()    {}

const Default_SGameover_Code uint32 = 2028

func (m *SGameover) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SGameover_Code
}

func (m *SGameover) GetHuType() uint32 {
	if m != nil && m.HuType != nil {
		return *m.HuType
	}
	return 0
}

func (m *SGameover) GetPaoSeat() uint32 {
	if m != nil && m.PaoSeat != nil {
		return *m.PaoSeat
	}
	return 0
}

func (m *SGameover) GetData() []*ProtoCount {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SGameover) GetLianCount() uint32 {
	if m != nil && m.LianCount != nil {
		return *m.LianCount
	}
	return 0
}

// 房间广播文字聊天
type CBroadcastChatText struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2043" json:"code,omitempty"`
	Content          []byte  `protobuf:"bytes,2,req,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CBroadcastChatText) Reset()         { *m = CBroadcastChatText{} }
func (m *CBroadcastChatText) String() string { return proto.CompactTextString(m) }
func (*CBroadcastChatText) ProtoMessage()    {}

const Default_CBroadcastChatText_Code uint32 = 2043

func (m *CBroadcastChatText) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CBroadcastChatText_Code
}

func (m *CBroadcastChatText) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// 房间广播语音聊天
type CBroadcastChat struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2044" json:"code,omitempty"`
	Content          []byte  `protobuf:"bytes,2,req,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CBroadcastChat) Reset()         { *m = CBroadcastChat{} }
func (m *CBroadcastChat) String() string { return proto.CompactTextString(m) }
func (*CBroadcastChat) ProtoMessage()    {}

const Default_CBroadcastChat_Code uint32 = 2044

func (m *CBroadcastChat) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CBroadcastChat_Code
}

func (m *CBroadcastChat) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// 广播文字聊天
type SBroadcastChatText struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2043" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Content          []byte  `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SBroadcastChatText) Reset()         { *m = SBroadcastChatText{} }
func (m *SBroadcastChatText) String() string { return proto.CompactTextString(m) }
func (*SBroadcastChatText) ProtoMessage()    {}

const Default_SBroadcastChatText_Code uint32 = 2043
const Default_SBroadcastChatText_Error uint32 = 0

func (m *SBroadcastChatText) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SBroadcastChatText_Code
}

func (m *SBroadcastChatText) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SBroadcastChatText) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *SBroadcastChatText) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SBroadcastChatText_Error
}

// 广播语音聊天
type SBroadcastChat struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2044" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Content          []byte  `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SBroadcastChat) Reset()         { *m = SBroadcastChat{} }
func (m *SBroadcastChat) String() string { return proto.CompactTextString(m) }
func (*SBroadcastChat) ProtoMessage()    {}

const Default_SBroadcastChat_Code uint32 = 2044
const Default_SBroadcastChat_Error uint32 = 0

func (m *SBroadcastChat) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SBroadcastChat_Code
}

func (m *SBroadcastChat) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SBroadcastChat) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *SBroadcastChat) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SBroadcastChat_Error
}

// 抢杠
type CQiangKong struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2048" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CQiangKong) Reset()         { *m = CQiangKong{} }
func (m *CQiangKong) String() string { return proto.CompactTextString(m) }
func (*CQiangKong) ProtoMessage()    {}

const Default_CQiangKong_Code uint32 = 2048

func (m *CQiangKong) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CQiangKong_Code
}

type SQiangKong struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2048" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	TargetSeat       *uint32 `protobuf:"varint,3,req,name=targetSeat" json:"targetSeat,omitempty"`
	Card             *uint32 `protobuf:"varint,4,req,name=card" json:"card,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SQiangKong) Reset()         { *m = SQiangKong{} }
func (m *SQiangKong) String() string { return proto.CompactTextString(m) }
func (*SQiangKong) ProtoMessage()    {}

const Default_SQiangKong_Code uint32 = 2048
const Default_SQiangKong_Error uint32 = 0

func (m *SQiangKong) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SQiangKong_Code
}

func (m *SQiangKong) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SQiangKong) GetTargetSeat() uint32 {
	if m != nil && m.TargetSeat != nil {
		return *m.TargetSeat
	}
	return 0
}

func (m *SQiangKong) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *SQiangKong) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SQiangKong_Error
}

// 买子，有点类似卡五星的"漂"
type CMaiZi struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2084" json:"code,omitempty"`
	Count            *uint32 `protobuf:"varint,2,req,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMaiZi) Reset()         { *m = CMaiZi{} }
func (m *CMaiZi) String() string { return proto.CompactTextString(m) }
func (*CMaiZi) ProtoMessage()    {}

const Default_CMaiZi_Code uint32 = 2084

func (m *CMaiZi) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CMaiZi_Code
}

func (m *CMaiZi) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

// 广播接口
type SMaiZi struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2084" json:"code,omitempty"`
	Count            *uint32 `protobuf:"varint,2,req,name=count" json:"count,omitempty"`
	Seat             *uint32 `protobuf:"varint,3,req,name=seat" json:"seat,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SMaiZi) Reset()         { *m = SMaiZi{} }
func (m *SMaiZi) String() string { return proto.CompactTextString(m) }
func (*SMaiZi) ProtoMessage()    {}

const Default_SMaiZi_Code uint32 = 2084
const Default_SMaiZi_Error uint32 = 0

func (m *SMaiZi) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SMaiZi_Code
}

func (m *SMaiZi) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *SMaiZi) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SMaiZi) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SMaiZi_Error
}

// 玩家离线和上线通知
type SOffline struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=2086" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Status           *bool   `protobuf:"varint,3,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SOffline) Reset()         { *m = SOffline{} }
func (m *SOffline) String() string { return proto.CompactTextString(m) }
func (*SOffline) ProtoMessage()    {}

const Default_SOffline_Code uint32 = 2086

func (m *SOffline) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SOffline_Code
}

func (m *SOffline) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SOffline) GetStatus() bool {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return false
}

func init() {
}
