// Code generated by protoc-gen-go.
// source: socialroom.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 进入私人房间,包括观众，断线重连，私人房间进入拍桌全部通用接口
type CEnterSocialRoom struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7001" json:"code,omitempty"`
	Invitecode       *string `protobuf:"bytes,2,req,name=invitecode" json:"invitecode,omitempty"`
	Longitude        *string `protobuf:"bytes,4,req,name=longitude" json:"longitude,omitempty"`
	Latitude         *string `protobuf:"bytes,5,req,name=latitude" json:"latitude,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CEnterSocialRoom) Reset()         { *m = CEnterSocialRoom{} }
func (m *CEnterSocialRoom) String() string { return proto.CompactTextString(m) }
func (*CEnterSocialRoom) ProtoMessage()    {}

const Default_CEnterSocialRoom_Code uint32 = 7001

func (m *CEnterSocialRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CEnterSocialRoom_Code
}

func (m *CEnterSocialRoom) GetInvitecode() string {
	if m != nil && m.Invitecode != nil {
		return *m.Invitecode
	}
	return ""
}

func (m *CEnterSocialRoom) GetLongitude() string {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return ""
}

func (m *CEnterSocialRoom) GetLatitude() string {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return ""
}

type SEnterSocialRoom struct {
	Code             *uint32      `protobuf:"varint,1,opt,name=code,def=7001" json:"code,omitempty"`
	Position         *uint32      `protobuf:"varint,2,req" json:"Position,omitempty"`
	Room             *RoomData    `protobuf:"bytes,3,req,name=room" json:"room,omitempty"`
	Userinfo         []*ProtoUser `protobuf:"bytes,4,rep,name=userinfo" json:"userinfo,omitempty"`
	Beginning        *bool        `protobuf:"varint,5,req,name=beginning" json:"beginning,omitempty"`
	CardsCount       *uint32      `protobuf:"varint,6,req,name=cardsCount" json:"cardsCount,omitempty"`
	Dice             *uint32      `protobuf:"varint,7,req,name=dice" json:"dice,omitempty"`
	KongCount        *uint32      `protobuf:"varint,8,req,name=kongCount" json:"kongCount,omitempty"`
	LuckyCard        *uint32      `protobuf:"varint,9,req,name=luckyCard" json:"luckyCard,omitempty"`
	Cards            []*ProtoCard `protobuf:"bytes,11,rep,name=cards" json:"cards,omitempty"`
	Turn             *uint32      `protobuf:"varint,12,req,name=turn" json:"turn,omitempty"`
	Handcards        []byte       `protobuf:"bytes,13,req,name=handcards" json:"handcards,omitempty"`
	Value            *int64       `protobuf:"varint,14,req,name=value" json:"value,omitempty"`
	Watchseat        *uint32      `protobuf:"varint,15,req,name=watchseat" json:"watchseat,omitempty"`
	Ready            *bool        `protobuf:"varint,16,req,name=ready" json:"ready,omitempty"`
	Score            *int32       `protobuf:"varint,17,req,name=score" json:"score,omitempty"`
	Ma               *uint32      `protobuf:"varint,18,req,name=ma" json:"ma,omitempty"`
	LaunchSeat       *uint32      `protobuf:"varint,19,req,name=launchSeat" json:"launchSeat,omitempty"`
	VoteAgree        []uint32     `protobuf:"varint,20,rep,name=voteAgree" json:"voteAgree,omitempty"`
	VoteDisagree     []uint32     `protobuf:"varint,21,rep,name=voteDisagree" json:"voteDisagree,omitempty"`
	ConferenceId     *string      `protobuf:"bytes,22,req,name=conferenceId" json:"conferenceId,omitempty"`
	Mazi             *int32       `protobuf:"varint,23,req,name=mazi" json:"mazi,omitempty"`
	Error            *uint32      `protobuf:"varint,24,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SEnterSocialRoom) Reset()         { *m = SEnterSocialRoom{} }
func (m *SEnterSocialRoom) String() string { return proto.CompactTextString(m) }
func (*SEnterSocialRoom) ProtoMessage()    {}

const Default_SEnterSocialRoom_Code uint32 = 7001
const Default_SEnterSocialRoom_Error uint32 = 0

func (m *SEnterSocialRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SEnterSocialRoom_Code
}

func (m *SEnterSocialRoom) GetPosition() uint32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *SEnterSocialRoom) GetRoom() *RoomData {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *SEnterSocialRoom) GetUserinfo() []*ProtoUser {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

func (m *SEnterSocialRoom) GetBeginning() bool {
	if m != nil && m.Beginning != nil {
		return *m.Beginning
	}
	return false
}

func (m *SEnterSocialRoom) GetCardsCount() uint32 {
	if m != nil && m.CardsCount != nil {
		return *m.CardsCount
	}
	return 0
}

func (m *SEnterSocialRoom) GetDice() uint32 {
	if m != nil && m.Dice != nil {
		return *m.Dice
	}
	return 0
}

func (m *SEnterSocialRoom) GetKongCount() uint32 {
	if m != nil && m.KongCount != nil {
		return *m.KongCount
	}
	return 0
}

func (m *SEnterSocialRoom) GetLuckyCard() uint32 {
	if m != nil && m.LuckyCard != nil {
		return *m.LuckyCard
	}
	return 0
}

func (m *SEnterSocialRoom) GetCards() []*ProtoCard {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *SEnterSocialRoom) GetTurn() uint32 {
	if m != nil && m.Turn != nil {
		return *m.Turn
	}
	return 0
}

func (m *SEnterSocialRoom) GetHandcards() []byte {
	if m != nil {
		return m.Handcards
	}
	return nil
}

func (m *SEnterSocialRoom) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SEnterSocialRoom) GetWatchseat() uint32 {
	if m != nil && m.Watchseat != nil {
		return *m.Watchseat
	}
	return 0
}

func (m *SEnterSocialRoom) GetReady() bool {
	if m != nil && m.Ready != nil {
		return *m.Ready
	}
	return false
}

func (m *SEnterSocialRoom) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *SEnterSocialRoom) GetMa() uint32 {
	if m != nil && m.Ma != nil {
		return *m.Ma
	}
	return 0
}

func (m *SEnterSocialRoom) GetLaunchSeat() uint32 {
	if m != nil && m.LaunchSeat != nil {
		return *m.LaunchSeat
	}
	return 0
}

func (m *SEnterSocialRoom) GetVoteAgree() []uint32 {
	if m != nil {
		return m.VoteAgree
	}
	return nil
}

func (m *SEnterSocialRoom) GetVoteDisagree() []uint32 {
	if m != nil {
		return m.VoteDisagree
	}
	return nil
}

func (m *SEnterSocialRoom) GetConferenceId() string {
	if m != nil && m.ConferenceId != nil {
		return *m.ConferenceId
	}
	return ""
}

func (m *SEnterSocialRoom) GetMazi() int32 {
	if m != nil && m.Mazi != nil {
		return *m.Mazi
	}
	return 0
}

func (m *SEnterSocialRoom) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SEnterSocialRoom_Error
}

// 私人局离开房间
type CPrivateLeave struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7006" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPrivateLeave) Reset()         { *m = CPrivateLeave{} }
func (m *CPrivateLeave) String() string { return proto.CompactTextString(m) }
func (*CPrivateLeave) ProtoMessage()    {}

const Default_CPrivateLeave_Code uint32 = 7006

func (m *CPrivateLeave) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CPrivateLeave_Code
}

type SPrivateLeave struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7006" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Error            *uint32 `protobuf:"varint,3,req,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SPrivateLeave) Reset()         { *m = SPrivateLeave{} }
func (m *SPrivateLeave) String() string { return proto.CompactTextString(m) }
func (*SPrivateLeave) ProtoMessage()    {}

const Default_SPrivateLeave_Code uint32 = 7006
const Default_SPrivateLeave_Error uint32 = 0

func (m *SPrivateLeave) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPrivateLeave_Code
}

func (m *SPrivateLeave) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SPrivateLeave) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SPrivateLeave_Error
}

// 私人局，准备游戏
type CReady struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7008" json:"code,omitempty"`
	Ready            *bool   `protobuf:"varint,2,req,name=ready" json:"ready,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CReady) Reset()         { *m = CReady{} }
func (m *CReady) String() string { return proto.CompactTextString(m) }
func (*CReady) ProtoMessage()    {}

const Default_CReady_Code uint32 = 7008

func (m *CReady) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CReady_Code
}

func (m *CReady) GetReady() bool {
	if m != nil && m.Ready != nil {
		return *m.Ready
	}
	return false
}

type SReady struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7008" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Ready            *bool   `protobuf:"varint,3,req,name=ready" json:"ready,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SReady) Reset()         { *m = SReady{} }
func (m *SReady) String() string { return proto.CompactTextString(m) }
func (*SReady) ProtoMessage()    {}

const Default_SReady_Code uint32 = 7008
const Default_SReady_Error uint32 = 0

func (m *SReady) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SReady_Code
}

func (m *SReady) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SReady) GetReady() bool {
	if m != nil && m.Ready != nil {
		return *m.Ready
	}
	return false
}

func (m *SReady) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SReady_Error
}

type SPrivateOver struct {
	Code             *uint32         `protobuf:"varint,1,opt,name=code,def=7009" json:"code,omitempty"`
	Cid              *uint32         `protobuf:"varint,2,req,name=cid" json:"cid,omitempty"`
	Roomid           *uint32         `protobuf:"varint,3,req,name=roomid" json:"roomid,omitempty"`
	Round            *uint32         `protobuf:"varint,4,req,name=round" json:"round,omitempty"`
	Expire           *uint32         `protobuf:"varint,5,req,name=expire" json:"expire,omitempty"`
	List             []*PrivateScore `protobuf:"bytes,6,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *SPrivateOver) Reset()         { *m = SPrivateOver{} }
func (m *SPrivateOver) String() string { return proto.CompactTextString(m) }
func (*SPrivateOver) ProtoMessage()    {}

const Default_SPrivateOver_Code uint32 = 7009

func (m *SPrivateOver) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPrivateOver_Code
}

func (m *SPrivateOver) GetCid() uint32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *SPrivateOver) GetRoomid() uint32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *SPrivateOver) GetRound() uint32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *SPrivateOver) GetExpire() uint32 {
	if m != nil && m.Expire != nil {
		return *m.Expire
	}
	return 0
}

func (m *SPrivateOver) GetList() []*PrivateScore {
	if m != nil {
		return m.List
	}
	return nil
}

type PrivateScore struct {
	Userid           *string `protobuf:"bytes,1,req,name=userid" json:"userid,omitempty"`
	Score            *int32  `protobuf:"varint,2,req,name=score" json:"score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PrivateScore) Reset()         { *m = PrivateScore{} }
func (m *PrivateScore) String() string { return proto.CompactTextString(m) }
func (*PrivateScore) ProtoMessage()    {}

func (m *PrivateScore) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *PrivateScore) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

// 进入房间7001，离开房间7006，准备游戏7008
// 私人局,创建房间
type CCreatePrivateRoom struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7010" json:"code,omitempty"`
	Rname            *string `protobuf:"bytes,2,req,name=rname" json:"rname,omitempty"`
	Rtype            *uint32 `protobuf:"varint,3,req,name=rtype" json:"rtype,omitempty"`
	Maizi            *bool   `protobuf:"varint,4,req,name=maizi" json:"maizi,omitempty"`
	Ante             *uint32 `protobuf:"varint,5,req,name=ante" json:"ante,omitempty"`
	Round            *uint32 `protobuf:"varint,6,req,name=round" json:"round,omitempty"`
	Payment          *uint32 `protobuf:"varint,7,req,name=payment" json:"payment,omitempty"`
	Ma               *uint32 `protobuf:"varint,8,req,name=ma" json:"ma,omitempty"`
	Longitude        *string `protobuf:"bytes,10,req,name=longitude" json:"longitude,omitempty"`
	Latitude         *string `protobuf:"bytes,11,req,name=latitude" json:"latitude,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCreatePrivateRoom) Reset()         { *m = CCreatePrivateRoom{} }
func (m *CCreatePrivateRoom) String() string { return proto.CompactTextString(m) }
func (*CCreatePrivateRoom) ProtoMessage()    {}

const Default_CCreatePrivateRoom_Code uint32 = 7010

func (m *CCreatePrivateRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CCreatePrivateRoom_Code
}

func (m *CCreatePrivateRoom) GetRname() string {
	if m != nil && m.Rname != nil {
		return *m.Rname
	}
	return ""
}

func (m *CCreatePrivateRoom) GetRtype() uint32 {
	if m != nil && m.Rtype != nil {
		return *m.Rtype
	}
	return 0
}

func (m *CCreatePrivateRoom) GetMaizi() bool {
	if m != nil && m.Maizi != nil {
		return *m.Maizi
	}
	return false
}

func (m *CCreatePrivateRoom) GetAnte() uint32 {
	if m != nil && m.Ante != nil {
		return *m.Ante
	}
	return 0
}

func (m *CCreatePrivateRoom) GetRound() uint32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *CCreatePrivateRoom) GetPayment() uint32 {
	if m != nil && m.Payment != nil {
		return *m.Payment
	}
	return 0
}

func (m *CCreatePrivateRoom) GetMa() uint32 {
	if m != nil && m.Ma != nil {
		return *m.Ma
	}
	return 0
}

func (m *CCreatePrivateRoom) GetLongitude() string {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return ""
}

func (m *CCreatePrivateRoom) GetLatitude() string {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return ""
}

// 返回房间数据,
type SCreatePrivateRoom struct {
	Code             *uint32   `protobuf:"varint,1,opt,name=code,def=7010" json:"code,omitempty"`
	Rdata            *RoomData `protobuf:"bytes,2,req,name=rdata" json:"rdata,omitempty"`
	Error            *uint32   `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SCreatePrivateRoom) Reset()         { *m = SCreatePrivateRoom{} }
func (m *SCreatePrivateRoom) String() string { return proto.CompactTextString(m) }
func (*SCreatePrivateRoom) ProtoMessage()    {}

const Default_SCreatePrivateRoom_Code uint32 = 7010
const Default_SCreatePrivateRoom_Error uint32 = 0

func (m *SCreatePrivateRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SCreatePrivateRoom_Code
}

func (m *SCreatePrivateRoom) GetRdata() *RoomData {
	if m != nil {
		return m.Rdata
	}
	return nil
}

func (m *SCreatePrivateRoom) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SCreatePrivateRoom_Error
}

// 私人局,通知房主可以开始游戏
type SStart struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7011" json:"code,omitempty"`
	Result           *uint32 `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SStart) Reset()         { *m = SStart{} }
func (m *SStart) String() string { return proto.CompactTextString(m) }
func (*SStart) ProtoMessage()    {}

const Default_SStart_Code uint32 = 7011

func (m *SStart) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SStart_Code
}

func (m *SStart) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 私人局,房主开始游戏
type CStartGame struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7012" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CStartGame) Reset()         { *m = CStartGame{} }
func (m *CStartGame) String() string { return proto.CompactTextString(m) }
func (*CStartGame) ProtoMessage()    {}

const Default_CStartGame_Code uint32 = 7012

func (m *CStartGame) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CStartGame_Code
}

type SStartGame struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7012" json:"code,omitempty"`
	Result           *uint32 `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SStartGame) Reset()         { *m = SStartGame{} }
func (m *SStartGame) String() string { return proto.CompactTextString(m) }
func (*SStartGame) ProtoMessage()    {}

const Default_SStartGame_Code uint32 = 7012
const Default_SStartGame_Error uint32 = 0

func (m *SStartGame) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SStartGame_Code
}

func (m *SStartGame) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SStartGame) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SStartGame_Error
}

// 私人局,发起投票申请解散房间
type CLaunchVote struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7014" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CLaunchVote) Reset()         { *m = CLaunchVote{} }
func (m *CLaunchVote) String() string { return proto.CompactTextString(m) }
func (*CLaunchVote) ProtoMessage()    {}

const Default_CLaunchVote_Code uint32 = 7014

func (m *CLaunchVote) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CLaunchVote_Code
}

type SLaunchVote struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7014" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SLaunchVote) Reset()         { *m = SLaunchVote{} }
func (m *SLaunchVote) String() string { return proto.CompactTextString(m) }
func (*SLaunchVote) ProtoMessage()    {}

const Default_SLaunchVote_Code uint32 = 7014

func (m *SLaunchVote) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SLaunchVote_Code
}

func (m *SLaunchVote) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SLaunchVote) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

// 私人局,发起投票,投票解散房间,如果投票成功，服务器主动推送SKick协议，并且reason字段值为1
type CVote struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7015" json:"code,omitempty"`
	Vote             *uint32 `protobuf:"varint,2,req,name=vote" json:"vote,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CVote) Reset()         { *m = CVote{} }
func (m *CVote) String() string { return proto.CompactTextString(m) }
func (*CVote) ProtoMessage()    {}

const Default_CVote_Code uint32 = 7015

func (m *CVote) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CVote_Code
}

func (m *CVote) GetVote() uint32 {
	if m != nil && m.Vote != nil {
		return *m.Vote
	}
	return 0
}

type SVote struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7015" json:"code,omitempty"`
	Vote             *uint32 `protobuf:"varint,2,req,name=vote" json:"vote,omitempty"`
	Seat             *uint32 `protobuf:"varint,3,req,name=seat" json:"seat,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SVote) Reset()         { *m = SVote{} }
func (m *SVote) String() string { return proto.CompactTextString(m) }
func (*SVote) ProtoMessage()    {}

const Default_SVote_Code uint32 = 7015

func (m *SVote) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SVote_Code
}

func (m *SVote) GetVote() uint32 {
	if m != nil && m.Vote != nil {
		return *m.Vote
	}
	return 0
}

func (m *SVote) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SVote) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

// 投票解散房间事件结果,服务器主动推送
type SVoteResult struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7016" json:"code,omitempty"`
	Vote             *uint32 `protobuf:"varint,2,req,name=vote" json:"vote,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SVoteResult) Reset()         { *m = SVoteResult{} }
func (m *SVoteResult) String() string { return proto.CompactTextString(m) }
func (*SVoteResult) ProtoMessage()    {}

const Default_SVoteResult_Code uint32 = 7016

func (m *SVoteResult) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SVoteResult_Code
}

func (m *SVoteResult) GetVote() uint32 {
	if m != nil && m.Vote != nil {
		return *m.Vote
	}
	return 0
}

type CPrivateRecord struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7017" json:"code,omitempty"`
	Page             *uint32 `protobuf:"varint,2,req,name=page" json:"page,omitempty"`
	PageMax          *uint32 `protobuf:"varint,3,req,name=pageMax" json:"pageMax,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPrivateRecord) Reset()         { *m = CPrivateRecord{} }
func (m *CPrivateRecord) String() string { return proto.CompactTextString(m) }
func (*CPrivateRecord) ProtoMessage()    {}

const Default_CPrivateRecord_Code uint32 = 7017

func (m *CPrivateRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CPrivateRecord_Code
}

func (m *CPrivateRecord) GetPage() uint32 {
	if m != nil && m.Page != nil {
		return *m.Page
	}
	return 0
}

func (m *CPrivateRecord) GetPageMax() uint32 {
	if m != nil && m.PageMax != nil {
		return *m.PageMax
	}
	return 0
}

type SPrivateRecord struct {
	Code             *uint32          `protobuf:"varint,1,opt,name=code,def=7017" json:"code,omitempty"`
	List             []*PrivateRecord `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error            *uint32          `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SPrivateRecord) Reset()         { *m = SPrivateRecord{} }
func (m *SPrivateRecord) String() string { return proto.CompactTextString(m) }
func (*SPrivateRecord) ProtoMessage()    {}

const Default_SPrivateRecord_Code uint32 = 7017
const Default_SPrivateRecord_Error uint32 = 0

func (m *SPrivateRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPrivateRecord_Code
}

func (m *SPrivateRecord) GetList() []*PrivateRecord {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SPrivateRecord) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SPrivateRecord_Error
}

// 获取玩家的私人房间记录
type PrivateRecord struct {
	Time             *uint32                 `protobuf:"varint,1,req,name=time" json:"time,omitempty"`
	Rid              *uint32                 `protobuf:"varint,2,req,name=rid" json:"rid,omitempty"`
	Invitecode       *string                 `protobuf:"bytes,3,req,name=invitecode" json:"invitecode,omitempty"`
	Rname            *string                 `protobuf:"bytes,4,req,name=rname" json:"rname,omitempty"`
	Ante             *uint32                 `protobuf:"varint,5,req,name=ante" json:"ante,omitempty"`
	TotalRound       *uint32                 `protobuf:"varint,6,req,name=totalRound" json:"totalRound,omitempty"`
	Ma               *uint32                 `protobuf:"varint,7,req,name=ma" json:"ma,omitempty"`
	Coin             *int32                  `protobuf:"varint,8,req,name=coin" json:"coin,omitempty"`
	Round            *uint32                 `protobuf:"varint,9,req,name=round" json:"round,omitempty"`
	List             []*PrivateRecordDetails `protobuf:"bytes,10,rep,name=list" json:"list,omitempty"`
	Lists            []*PrivateRecords       `protobuf:"bytes,11,rep,name=lists" json:"lists,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *PrivateRecord) Reset()         { *m = PrivateRecord{} }
func (m *PrivateRecord) String() string { return proto.CompactTextString(m) }
func (*PrivateRecord) ProtoMessage()    {}

func (m *PrivateRecord) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *PrivateRecord) GetRid() uint32 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *PrivateRecord) GetInvitecode() string {
	if m != nil && m.Invitecode != nil {
		return *m.Invitecode
	}
	return ""
}

func (m *PrivateRecord) GetRname() string {
	if m != nil && m.Rname != nil {
		return *m.Rname
	}
	return ""
}

func (m *PrivateRecord) GetAnte() uint32 {
	if m != nil && m.Ante != nil {
		return *m.Ante
	}
	return 0
}

func (m *PrivateRecord) GetTotalRound() uint32 {
	if m != nil && m.TotalRound != nil {
		return *m.TotalRound
	}
	return 0
}

func (m *PrivateRecord) GetMa() uint32 {
	if m != nil && m.Ma != nil {
		return *m.Ma
	}
	return 0
}

func (m *PrivateRecord) GetCoin() int32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *PrivateRecord) GetRound() uint32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *PrivateRecord) GetList() []*PrivateRecordDetails {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *PrivateRecord) GetLists() []*PrivateRecords {
	if m != nil {
		return m.Lists
	}
	return nil
}

type PrivateRecordDetails struct {
	Seat             *uint32 `protobuf:"varint,1,req,name=seat" json:"seat,omitempty"`
	Userid           *string `protobuf:"bytes,2,req,name=userid" json:"userid,omitempty"`
	Uname            *string `protobuf:"bytes,3,req,name=uname" json:"uname,omitempty"`
	Sex              *uint32 `protobuf:"varint,4,req,name=sex" json:"sex,omitempty"`
	Photo            *string `protobuf:"bytes,5,req,name=photo" json:"photo,omitempty"`
	Coin             *int32  `protobuf:"varint,6,req,name=coin" json:"coin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PrivateRecordDetails) Reset()         { *m = PrivateRecordDetails{} }
func (m *PrivateRecordDetails) String() string { return proto.CompactTextString(m) }
func (*PrivateRecordDetails) ProtoMessage()    {}

func (m *PrivateRecordDetails) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *PrivateRecordDetails) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *PrivateRecordDetails) GetUname() string {
	if m != nil && m.Uname != nil {
		return *m.Uname
	}
	return ""
}

func (m *PrivateRecordDetails) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *PrivateRecordDetails) GetPhoto() string {
	if m != nil && m.Photo != nil {
		return *m.Photo
	}
	return ""
}

func (m *PrivateRecordDetails) GetCoin() int32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

// 一局一局展示协议
type PrivateRecords struct {
	Round            *uint32           `protobuf:"varint,1,req,name=round" json:"round,omitempty"`
	List             []*PrivateDetails `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PrivateRecords) Reset()         { *m = PrivateRecords{} }
func (m *PrivateRecords) String() string { return proto.CompactTextString(m) }
func (*PrivateRecords) ProtoMessage()    {}

func (m *PrivateRecords) GetRound() uint32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *PrivateRecords) GetList() []*PrivateDetails {
	if m != nil {
		return m.List
	}
	return nil
}

// 当局输赢情况
type PrivateDetails struct {
	Uname            *string `protobuf:"bytes,1,req,name=uname" json:"uname,omitempty"`
	Coin             *int32  `protobuf:"varint,2,req,name=coin" json:"coin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PrivateDetails) Reset()         { *m = PrivateDetails{} }
func (m *PrivateDetails) String() string { return proto.CompactTextString(m) }
func (*PrivateDetails) ProtoMessage()    {}

func (m *PrivateDetails) GetUname() string {
	if m != nil && m.Uname != nil {
		return *m.Uname
	}
	return ""
}

func (m *PrivateDetails) GetCoin() int32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

//   根据私人房房间号,获取记录该房间所以记录
type CPRecordByRid struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7019" json:"code,omitempty"`
	Rid              *uint32 `protobuf:"varint,2,req,name=rid" json:"rid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPRecordByRid) Reset()         { *m = CPRecordByRid{} }
func (m *CPRecordByRid) String() string { return proto.CompactTextString(m) }
func (*CPRecordByRid) ProtoMessage()    {}

const Default_CPRecordByRid_Code uint32 = 7019

func (m *CPRecordByRid) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CPRecordByRid_Code
}

func (m *CPRecordByRid) GetRid() uint32 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

type SPRecordByRid struct {
	Code             *uint32                 `protobuf:"varint,1,opt,name=code,def=7019" json:"code,omitempty"`
	Time             *uint32                 `protobuf:"varint,2,req,name=time" json:"time,omitempty"`
	Rid              *uint32                 `protobuf:"varint,3,req,name=rid" json:"rid,omitempty"`
	Invitecode       *string                 `protobuf:"bytes,4,req,name=invitecode" json:"invitecode,omitempty"`
	Rname            *string                 `protobuf:"bytes,5,req,name=rname" json:"rname,omitempty"`
	Ante             *uint32                 `protobuf:"varint,6,req,name=ante" json:"ante,omitempty"`
	TotalRound       *uint32                 `protobuf:"varint,7,req,name=totalRound" json:"totalRound,omitempty"`
	Ma               *uint32                 `protobuf:"varint,8,req,name=ma" json:"ma,omitempty"`
	List             []*PrivateRecordDetails `protobuf:"bytes,9,rep,name=list" json:"list,omitempty"`
	Error            *uint32                 `protobuf:"varint,10,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *SPRecordByRid) Reset()         { *m = SPRecordByRid{} }
func (m *SPRecordByRid) String() string { return proto.CompactTextString(m) }
func (*SPRecordByRid) ProtoMessage()    {}

const Default_SPRecordByRid_Code uint32 = 7019
const Default_SPRecordByRid_Error uint32 = 0

func (m *SPRecordByRid) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPRecordByRid_Code
}

func (m *SPRecordByRid) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *SPRecordByRid) GetRid() uint32 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *SPRecordByRid) GetInvitecode() string {
	if m != nil && m.Invitecode != nil {
		return *m.Invitecode
	}
	return ""
}

func (m *SPRecordByRid) GetRname() string {
	if m != nil && m.Rname != nil {
		return *m.Rname
	}
	return ""
}

func (m *SPRecordByRid) GetAnte() uint32 {
	if m != nil && m.Ante != nil {
		return *m.Ante
	}
	return 0
}

func (m *SPRecordByRid) GetTotalRound() uint32 {
	if m != nil && m.TotalRound != nil {
		return *m.TotalRound
	}
	return 0
}

func (m *SPRecordByRid) GetMa() uint32 {
	if m != nil && m.Ma != nil {
		return *m.Ma
	}
	return 0
}

func (m *SPRecordByRid) GetList() []*PrivateRecordDetails {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SPRecordByRid) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SPRecordByRid_Error
}

func init() {
}
