// Code generated by protoc-gen-go.
// source: sys.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type CPing struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9000" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPing) Reset()         { *m = CPing{} }
func (m *CPing) String() string { return proto.CompactTextString(m) }
func (*CPing) ProtoMessage()    {}

const Default_CPing_Code uint32 = 9000

func (m *CPing) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CPing_Code
}

type SPing struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9000" json:"code,omitempty"`
	Error            *uint32 `protobuf:"varint,2,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SPing) Reset()         { *m = SPing{} }
func (m *SPing) String() string { return proto.CompactTextString(m) }
func (*SPing) ProtoMessage()    {}

const Default_SPing_Code uint32 = 9000
const Default_SPing_Error uint32 = 0

func (m *SPing) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPing_Code
}

func (m *SPing) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SPing_Error
}

type CFeedback struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9002" json:"code,omitempty"`
	Content          *string `protobuf:"bytes,2,req,name=content" json:"content,omitempty"`
	Kind             *uint32 `protobuf:"varint,3,req,name=kind" json:"kind,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CFeedback) Reset()         { *m = CFeedback{} }
func (m *CFeedback) String() string { return proto.CompactTextString(m) }
func (*CFeedback) ProtoMessage()    {}

const Default_CFeedback_Code uint32 = 9002

func (m *CFeedback) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CFeedback_Code
}

func (m *CFeedback) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *CFeedback) GetKind() uint32 {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return 0
}

type SFeedback struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9002" json:"code,omitempty"`
	Error            *uint32 `protobuf:"varint,2,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SFeedback) Reset()         { *m = SFeedback{} }
func (m *SFeedback) String() string { return proto.CompactTextString(m) }
func (*SFeedback) ProtoMessage()    {}

const Default_SFeedback_Code uint32 = 9002
const Default_SFeedback_Error uint32 = 0

func (m *SFeedback) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SFeedback_Code
}

func (m *SFeedback) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SFeedback_Error
}

// 公告
type CNotice struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9003" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CNotice) Reset()         { *m = CNotice{} }
func (m *CNotice) String() string { return proto.CompactTextString(m) }
func (*CNotice) ProtoMessage()    {}

const Default_CNotice_Code uint32 = 9003

func (m *CNotice) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CNotice_Code
}

// 公告
type SNotice struct {
	Code             *uint32   `protobuf:"varint,1,opt,name=code,def=9003" json:"code,omitempty"`
	List             []*Notice `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error            *uint32   `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SNotice) Reset()         { *m = SNotice{} }
func (m *SNotice) String() string { return proto.CompactTextString(m) }
func (*SNotice) ProtoMessage()    {}

const Default_SNotice_Code uint32 = 9003
const Default_SNotice_Error uint32 = 0

func (m *SNotice) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SNotice_Code
}

func (m *SNotice) GetList() []*Notice {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SNotice) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SNotice_Error
}

// 公告
type Notice struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Title            *string `protobuf:"bytes,3,req,name=title" json:"title,omitempty"`
	Content          *string `protobuf:"bytes,4,req,name=content" json:"content,omitempty"`
	Time             *uint32 `protobuf:"varint,5,req,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Notice) Reset()         { *m = Notice{} }
func (m *Notice) String() string { return proto.CompactTextString(m) }
func (*Notice) ProtoMessage()    {}

func (m *Notice) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Notice) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Notice) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Notice) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *Notice) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

// 商城
type CBuy struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9006" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CBuy) Reset()         { *m = CBuy{} }
func (m *CBuy) String() string { return proto.CompactTextString(m) }
func (*CBuy) ProtoMessage()    {}

const Default_CBuy_Code uint32 = 9006

func (m *CBuy) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CBuy_Code
}

func (m *CBuy) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type SBuy struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9006" json:"code,omitempty"`
	Result           *uint32 `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SBuy) Reset()         { *m = SBuy{} }
func (m *SBuy) String() string { return proto.CompactTextString(m) }
func (*SBuy) ProtoMessage()    {}

const Default_SBuy_Code uint32 = 9006
const Default_SBuy_Error uint32 = 0

func (m *SBuy) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SBuy_Code
}

func (m *SBuy) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SBuy) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SBuy_Error
}

// 绑定玩家id
type CBuild struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9007" json:"code,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CBuild) Reset()         { *m = CBuild{} }
func (m *CBuild) String() string { return proto.CompactTextString(m) }
func (*CBuild) ProtoMessage()    {}

const Default_CBuild_Code uint32 = 9007

func (m *CBuild) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CBuild_Code
}

func (m *CBuild) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type SBuild struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9007" json:"code,omitempty"`
	Result           *uint32 `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SBuild) Reset()         { *m = SBuild{} }
func (m *SBuild) String() string { return proto.CompactTextString(m) }
func (*SBuild) ProtoMessage()    {}

const Default_SBuild_Code uint32 = 9007
const Default_SBuild_Error uint32 = 0

func (m *SBuild) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SBuild_Code
}

func (m *SBuild) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SBuild) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SBuild_Error
}

// 获取活动列表
type CActivity struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9010" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CActivity) Reset()         { *m = CActivity{} }
func (m *CActivity) String() string { return proto.CompactTextString(m) }
func (*CActivity) ProtoMessage()    {}

const Default_CActivity_Code uint32 = 9010

func (m *CActivity) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CActivity_Code
}

type ProtoActivity struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Count            *uint32 `protobuf:"varint,3,req,name=count" json:"count,omitempty"`
	Rewards          *uint32 `protobuf:"varint,4,req,name=rewards" json:"rewards,omitempty"`
	Starttime        *uint32 `protobuf:"varint,5,req,name=starttime" json:"starttime,omitempty"`
	Endtime          *uint32 `protobuf:"varint,6,req,name=endtime" json:"endtime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoActivity) Reset()         { *m = ProtoActivity{} }
func (m *ProtoActivity) String() string { return proto.CompactTextString(m) }
func (*ProtoActivity) ProtoMessage()    {}

func (m *ProtoActivity) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoActivity) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ProtoActivity) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ProtoActivity) GetRewards() uint32 {
	if m != nil && m.Rewards != nil {
		return *m.Rewards
	}
	return 0
}

func (m *ProtoActivity) GetStarttime() uint32 {
	if m != nil && m.Starttime != nil {
		return *m.Starttime
	}
	return 0
}

func (m *ProtoActivity) GetEndtime() uint32 {
	if m != nil && m.Endtime != nil {
		return *m.Endtime
	}
	return 0
}

type SActivity struct {
	Code             *uint32          `protobuf:"varint,1,opt,name=code,def=9010" json:"code,omitempty"`
	List             []*ProtoActivity `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error            *uint32          `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SActivity) Reset()         { *m = SActivity{} }
func (m *SActivity) String() string { return proto.CompactTextString(m) }
func (*SActivity) ProtoMessage()    {}

const Default_SActivity_Code uint32 = 9010
const Default_SActivity_Error uint32 = 0

func (m *SActivity) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SActivity_Code
}

func (m *SActivity) GetList() []*ProtoActivity {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SActivity) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SActivity_Error
}

// 活动领奖
type CGetActivityRewards struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9011" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGetActivityRewards) Reset()         { *m = CGetActivityRewards{} }
func (m *CGetActivityRewards) String() string { return proto.CompactTextString(m) }
func (*CGetActivityRewards) ProtoMessage()    {}

const Default_CGetActivityRewards_Code uint32 = 9011

func (m *CGetActivityRewards) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CGetActivityRewards_Code
}

func (m *CGetActivityRewards) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type SGetActivityRewards struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9011" json:"code,omitempty"`
	Error            *uint32 `protobuf:"varint,2,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SGetActivityRewards) Reset()         { *m = SGetActivityRewards{} }
func (m *SGetActivityRewards) String() string { return proto.CompactTextString(m) }
func (*SGetActivityRewards) ProtoMessage()    {}

const Default_SGetActivityRewards_Code uint32 = 9011
const Default_SGetActivityRewards_Error uint32 = 0

func (m *SGetActivityRewards) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SGetActivityRewards_Code
}

func (m *SGetActivityRewards) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SGetActivityRewards_Error
}

// 更新活动
type SUpdateActivity struct {
	Code             *uint32          `protobuf:"varint,1,opt,name=code,def=9012" json:"code,omitempty"`
	List             []*ProtoActivity `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SUpdateActivity) Reset()         { *m = SUpdateActivity{} }
func (m *SUpdateActivity) String() string { return proto.CompactTextString(m) }
func (*SUpdateActivity) ProtoMessage()    {}

const Default_SUpdateActivity_Code uint32 = 9012

func (m *SUpdateActivity) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SUpdateActivity_Code
}

func (m *SUpdateActivity) GetList() []*ProtoActivity {
	if m != nil {
		return m.List
	}
	return nil
}

// 分享邀请好友活动
type CWechatShare struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9013" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CWechatShare) Reset()         { *m = CWechatShare{} }
func (m *CWechatShare) String() string { return proto.CompactTextString(m) }
func (*CWechatShare) ProtoMessage()    {}

const Default_CWechatShare_Code uint32 = 9013

func (m *CWechatShare) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CWechatShare_Code
}

// 兑换
type CTradeList struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9020" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CTradeList) Reset()         { *m = CTradeList{} }
func (m *CTradeList) String() string { return proto.CompactTextString(m) }
func (*CTradeList) ProtoMessage()    {}

const Default_CTradeList_Code uint32 = 9020

func (m *CTradeList) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CTradeList_Code
}

type STradeList struct {
	Code             *uint32       `protobuf:"varint,1,opt,name=code,def=9020" json:"code,omitempty"`
	List             []*ProtoTrade `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error            *uint32       `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *STradeList) Reset()         { *m = STradeList{} }
func (m *STradeList) String() string { return proto.CompactTextString(m) }
func (*STradeList) ProtoMessage()    {}

const Default_STradeList_Code uint32 = 9020
const Default_STradeList_Error uint32 = 0

func (m *STradeList) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_STradeList_Code
}

func (m *STradeList) GetList() []*ProtoTrade {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *STradeList) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_STradeList_Error
}

type ProtoTrade struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Count            *uint32 `protobuf:"varint,2,req,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoTrade) Reset()         { *m = ProtoTrade{} }
func (m *ProtoTrade) String() string { return proto.CompactTextString(m) }
func (*ProtoTrade) ProtoMessage()    {}

func (m *ProtoTrade) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoTrade) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type CTradeRecord struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9021" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CTradeRecord) Reset()         { *m = CTradeRecord{} }
func (m *CTradeRecord) String() string { return proto.CompactTextString(m) }
func (*CTradeRecord) ProtoMessage()    {}

const Default_CTradeRecord_Code uint32 = 9021

func (m *CTradeRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CTradeRecord_Code
}

type STradeRecord struct {
	Code             *uint32             `protobuf:"varint,1,opt,name=code,def=9021" json:"code,omitempty"`
	List             []*ProtoTradeRecard `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error            *uint32             `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *STradeRecord) Reset()         { *m = STradeRecord{} }
func (m *STradeRecord) String() string { return proto.CompactTextString(m) }
func (*STradeRecord) ProtoMessage()    {}

const Default_STradeRecord_Code uint32 = 9021
const Default_STradeRecord_Error uint32 = 0

func (m *STradeRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_STradeRecord_Code
}

func (m *STradeRecord) GetList() []*ProtoTradeRecard {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *STradeRecord) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_STradeRecord_Error
}

type ProtoTradeRecard struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Time             *uint32 `protobuf:"varint,2,req,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoTradeRecard) Reset()         { *m = ProtoTradeRecard{} }
func (m *ProtoTradeRecard) String() string { return proto.CompactTextString(m) }
func (*ProtoTradeRecard) ProtoMessage()    {}

func (m *ProtoTradeRecard) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoTradeRecard) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

type CTradeUserInfo struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9022" json:"code,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Phone            *string `protobuf:"bytes,3,req,name=phone" json:"phone,omitempty"`
	Address          *string `protobuf:"bytes,4,req,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CTradeUserInfo) Reset()         { *m = CTradeUserInfo{} }
func (m *CTradeUserInfo) String() string { return proto.CompactTextString(m) }
func (*CTradeUserInfo) ProtoMessage()    {}

const Default_CTradeUserInfo_Code uint32 = 9022

func (m *CTradeUserInfo) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CTradeUserInfo_Code
}

func (m *CTradeUserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CTradeUserInfo) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *CTradeUserInfo) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

type STradeUserInfo struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9022" json:"code,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Phone            *string `protobuf:"bytes,3,req,name=phone" json:"phone,omitempty"`
	Address          *string `protobuf:"bytes,4,req,name=address" json:"address,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STradeUserInfo) Reset()         { *m = STradeUserInfo{} }
func (m *STradeUserInfo) String() string { return proto.CompactTextString(m) }
func (*STradeUserInfo) ProtoMessage()    {}

const Default_STradeUserInfo_Code uint32 = 9022
const Default_STradeUserInfo_Error uint32 = 0

func (m *STradeUserInfo) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_STradeUserInfo_Code
}

func (m *STradeUserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *STradeUserInfo) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *STradeUserInfo) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *STradeUserInfo) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_STradeUserInfo_Error
}

type CTrade struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9023" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CTrade) Reset()         { *m = CTrade{} }
func (m *CTrade) String() string { return proto.CompactTextString(m) }
func (*CTrade) ProtoMessage()    {}

const Default_CTrade_Code uint32 = 9023

func (m *CTrade) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CTrade_Code
}

func (m *CTrade) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type STrade struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9023" json:"code,omitempty"`
	Result           *uint32 `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	Id               *uint32 `protobuf:"varint,3,req,name=id" json:"id,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STrade) Reset()         { *m = STrade{} }
func (m *STrade) String() string { return proto.CompactTextString(m) }
func (*STrade) ProtoMessage()    {}

const Default_STrade_Code uint32 = 9023
const Default_STrade_Error uint32 = 0

func (m *STrade) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_STrade_Code
}

func (m *STrade) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *STrade) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *STrade) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_STrade_Error
}

// 爱贝支付 - 下单
type CIapppayOrder struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9050" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CIapppayOrder) Reset()         { *m = CIapppayOrder{} }
func (m *CIapppayOrder) String() string { return proto.CompactTextString(m) }
func (*CIapppayOrder) ProtoMessage()    {}

const Default_CIapppayOrder_Code uint32 = 9050

func (m *CIapppayOrder) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CIapppayOrder_Code
}

func (m *CIapppayOrder) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type SIapppayOrder struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9050" json:"code,omitempty"`
	Transid          *string `protobuf:"bytes,2,req,name=transid" json:"transid,omitempty"`
	Id               *uint32 `protobuf:"varint,3,req,name=id" json:"id,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SIapppayOrder) Reset()         { *m = SIapppayOrder{} }
func (m *SIapppayOrder) String() string { return proto.CompactTextString(m) }
func (*SIapppayOrder) ProtoMessage()    {}

const Default_SIapppayOrder_Code uint32 = 9050
const Default_SIapppayOrder_Error uint32 = 0

func (m *SIapppayOrder) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SIapppayOrder_Code
}

func (m *SIapppayOrder) GetTransid() string {
	if m != nil && m.Transid != nil {
		return *m.Transid
	}
	return ""
}

func (m *SIapppayOrder) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SIapppayOrder) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SIapppayOrder_Error
}

//  苹果支付
type CApplePay struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9052" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Receipt          *string `protobuf:"bytes,3,req,name=receipt" json:"receipt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CApplePay) Reset()         { *m = CApplePay{} }
func (m *CApplePay) String() string { return proto.CompactTextString(m) }
func (*CApplePay) ProtoMessage()    {}

const Default_CApplePay_Code uint32 = 9052

func (m *CApplePay) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CApplePay_Code
}

func (m *CApplePay) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CApplePay) GetReceipt() string {
	if m != nil && m.Receipt != nil {
		return *m.Receipt
	}
	return ""
}

type SApplePay struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9052" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SApplePay) Reset()         { *m = SApplePay{} }
func (m *SApplePay) String() string { return proto.CompactTextString(m) }
func (*SApplePay) ProtoMessage()    {}

const Default_SApplePay_Code uint32 = 9052
const Default_SApplePay_Error uint32 = 0

func (m *SApplePay) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SApplePay_Code
}

func (m *SApplePay) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SApplePay) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SApplePay_Error
}

// 微信支付 - 下单
type CWxpayOrder struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9053" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Body             *string `protobuf:"bytes,3,req,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CWxpayOrder) Reset()         { *m = CWxpayOrder{} }
func (m *CWxpayOrder) String() string { return proto.CompactTextString(m) }
func (*CWxpayOrder) ProtoMessage()    {}

const Default_CWxpayOrder_Code uint32 = 9053

func (m *CWxpayOrder) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CWxpayOrder_Code
}

func (m *CWxpayOrder) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CWxpayOrder) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

type SWxpayOrder struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9053" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Payreq           *string `protobuf:"bytes,3,req,name=payreq" json:"payreq,omitempty"`
	Orderid          *string `protobuf:"bytes,4,req,name=orderid" json:"orderid,omitempty"`
	Noncestr         *string `protobuf:"bytes,5,req,name=noncestr" json:"noncestr,omitempty"`
	Error            *uint32 `protobuf:"varint,6,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SWxpayOrder) Reset()         { *m = SWxpayOrder{} }
func (m *SWxpayOrder) String() string { return proto.CompactTextString(m) }
func (*SWxpayOrder) ProtoMessage()    {}

const Default_SWxpayOrder_Code uint32 = 9053
const Default_SWxpayOrder_Error uint32 = 0

func (m *SWxpayOrder) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SWxpayOrder_Code
}

func (m *SWxpayOrder) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SWxpayOrder) GetPayreq() string {
	if m != nil && m.Payreq != nil {
		return *m.Payreq
	}
	return ""
}

func (m *SWxpayOrder) GetOrderid() string {
	if m != nil && m.Orderid != nil {
		return *m.Orderid
	}
	return ""
}

func (m *SWxpayOrder) GetNoncestr() string {
	if m != nil && m.Noncestr != nil {
		return *m.Noncestr
	}
	return ""
}

func (m *SWxpayOrder) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SWxpayOrder_Error
}

// 微信支付 - 查询
type CWxpayQuery struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9054" json:"code,omitempty"`
	Transid          *string `protobuf:"bytes,2,req,name=transid" json:"transid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CWxpayQuery) Reset()         { *m = CWxpayQuery{} }
func (m *CWxpayQuery) String() string { return proto.CompactTextString(m) }
func (*CWxpayQuery) ProtoMessage()    {}

const Default_CWxpayQuery_Code uint32 = 9054

func (m *CWxpayQuery) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CWxpayQuery_Code
}

func (m *CWxpayQuery) GetTransid() string {
	if m != nil && m.Transid != nil {
		return *m.Transid
	}
	return ""
}

type SWxpayQuery struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9054" json:"code,omitempty"`
	Orderid          *string `protobuf:"bytes,2,req,name=orderid" json:"orderid,omitempty"`
	Result           *uint32 `protobuf:"varint,3,req,name=result" json:"result,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SWxpayQuery) Reset()         { *m = SWxpayQuery{} }
func (m *SWxpayQuery) String() string { return proto.CompactTextString(m) }
func (*SWxpayQuery) ProtoMessage()    {}

const Default_SWxpayQuery_Code uint32 = 9054
const Default_SWxpayQuery_Error uint32 = 0

func (m *SWxpayQuery) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SWxpayQuery_Code
}

func (m *SWxpayQuery) GetOrderid() string {
	if m != nil && m.Orderid != nil {
		return *m.Orderid
	}
	return ""
}

func (m *SWxpayQuery) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SWxpayQuery) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SWxpayQuery_Error
}

func init() {
}
