// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 更改用户名
type CChangeNickname struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1901" json:"code,omitempty"`
	Nickname         *string `protobuf:"bytes,2,req,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CChangeNickname) Reset()         { *m = CChangeNickname{} }
func (m *CChangeNickname) String() string { return proto.CompactTextString(m) }
func (*CChangeNickname) ProtoMessage()    {}

const Default_CChangeNickname_Code uint32 = 1901

func (m *CChangeNickname) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CChangeNickname_Code
}

func (m *CChangeNickname) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

type SChangeNickname struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1901" json:"code,omitempty"`
	Nickname         *string `protobuf:"bytes,2,req,name=nickname" json:"nickname,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SChangeNickname) Reset()         { *m = SChangeNickname{} }
func (m *SChangeNickname) String() string { return proto.CompactTextString(m) }
func (*SChangeNickname) ProtoMessage()    {}

const Default_SChangeNickname_Code uint32 = 1901
const Default_SChangeNickname_Error uint32 = 0

func (m *SChangeNickname) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SChangeNickname_Code
}

func (m *SChangeNickname) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *SChangeNickname) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SChangeNickname_Error
}

// 更改用户性别
type CChangeSex struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1902" json:"code,omitempty"`
	Sex              *uint32 `protobuf:"varint,2,req,name=sex" json:"sex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CChangeSex) Reset()         { *m = CChangeSex{} }
func (m *CChangeSex) String() string { return proto.CompactTextString(m) }
func (*CChangeSex) ProtoMessage()    {}

const Default_CChangeSex_Code uint32 = 1902

func (m *CChangeSex) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CChangeSex_Code
}

func (m *CChangeSex) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

type SChangeSex struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1902" json:"code,omitempty"`
	Sex              *uint32 `protobuf:"varint,2,req,name=sex" json:"sex,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SChangeSex) Reset()         { *m = SChangeSex{} }
func (m *SChangeSex) String() string { return proto.CompactTextString(m) }
func (*SChangeSex) ProtoMessage()    {}

const Default_SChangeSex_Code uint32 = 1902
const Default_SChangeSex_Error uint32 = 0

func (m *SChangeSex) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SChangeSex_Code
}

func (m *SChangeSex) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *SChangeSex) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SChangeSex_Error
}

//  战绩
type CArchieve struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1904" json:"code,omitempty"`
	Userid           *string `protobuf:"bytes,2,req,name=userid" json:"userid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CArchieve) Reset()         { *m = CArchieve{} }
func (m *CArchieve) String() string { return proto.CompactTextString(m) }
func (*CArchieve) ProtoMessage()    {}

const Default_CArchieve_Code uint32 = 1904

func (m *CArchieve) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CArchieve_Code
}

func (m *CArchieve) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

type SArchieve struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1904" json:"code,omitempty"`
	Best             *string `protobuf:"bytes,2,req,name=best" json:"best,omitempty"`
	Maxcoin          *uint32 `protobuf:"varint,3,req,name=maxcoin" json:"maxcoin,omitempty"`
	Gaincoin         *uint32 `protobuf:"varint,4,req,name=gaincoin" json:"gaincoin,omitempty"`
	Singlecoin       *uint32 `protobuf:"varint,5,req,name=singlecoin" json:"singlecoin,omitempty"`
	Qinglongdui      *uint32 `protobuf:"varint,6,req,name=qinglongdui" json:"qinglongdui,omitempty"`
	Longqi           *uint32 `protobuf:"varint,7,req,name=longqi" json:"longqi,omitempty"`
	Qingqi           *uint32 `protobuf:"varint,8,req,name=qingqi" json:"qingqi,omitempty"`
	Qingdui          *uint32 `protobuf:"varint,9,req,name=qingdui" json:"qingdui,omitempty"`
	Qing             *uint32 `protobuf:"varint,10,req,name=qing" json:"qing,omitempty"`
	Qidui            *uint32 `protobuf:"varint,11,req,name=qidui" json:"qidui,omitempty"`
	Pengpenghu       *uint32 `protobuf:"varint,12,req,name=pengpenghu" json:"pengpenghu,omitempty"`
	Tianhu           *uint32 `protobuf:"varint,13,req,name=tianhu" json:"tianhu,omitempty"`
	Dihu             *uint32 `protobuf:"varint,14,req,name=dihu" json:"dihu,omitempty"`
	Userid           *string `protobuf:"bytes,15,req,name=userid" json:"userid,omitempty"`
	Hutype           *uint32 `protobuf:"varint,16,req,name=hutype" json:"hutype,omitempty"`
	Error            *uint32 `protobuf:"varint,17,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SArchieve) Reset()         { *m = SArchieve{} }
func (m *SArchieve) String() string { return proto.CompactTextString(m) }
func (*SArchieve) ProtoMessage()    {}

const Default_SArchieve_Code uint32 = 1904
const Default_SArchieve_Error uint32 = 0

func (m *SArchieve) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SArchieve_Code
}

func (m *SArchieve) GetBest() string {
	if m != nil && m.Best != nil {
		return *m.Best
	}
	return ""
}

func (m *SArchieve) GetMaxcoin() uint32 {
	if m != nil && m.Maxcoin != nil {
		return *m.Maxcoin
	}
	return 0
}

func (m *SArchieve) GetGaincoin() uint32 {
	if m != nil && m.Gaincoin != nil {
		return *m.Gaincoin
	}
	return 0
}

func (m *SArchieve) GetSinglecoin() uint32 {
	if m != nil && m.Singlecoin != nil {
		return *m.Singlecoin
	}
	return 0
}

func (m *SArchieve) GetQinglongdui() uint32 {
	if m != nil && m.Qinglongdui != nil {
		return *m.Qinglongdui
	}
	return 0
}

func (m *SArchieve) GetLongqi() uint32 {
	if m != nil && m.Longqi != nil {
		return *m.Longqi
	}
	return 0
}

func (m *SArchieve) GetQingqi() uint32 {
	if m != nil && m.Qingqi != nil {
		return *m.Qingqi
	}
	return 0
}

func (m *SArchieve) GetQingdui() uint32 {
	if m != nil && m.Qingdui != nil {
		return *m.Qingdui
	}
	return 0
}

func (m *SArchieve) GetQing() uint32 {
	if m != nil && m.Qing != nil {
		return *m.Qing
	}
	return 0
}

func (m *SArchieve) GetQidui() uint32 {
	if m != nil && m.Qidui != nil {
		return *m.Qidui
	}
	return 0
}

func (m *SArchieve) GetPengpenghu() uint32 {
	if m != nil && m.Pengpenghu != nil {
		return *m.Pengpenghu
	}
	return 0
}

func (m *SArchieve) GetTianhu() uint32 {
	if m != nil && m.Tianhu != nil {
		return *m.Tianhu
	}
	return 0
}

func (m *SArchieve) GetDihu() uint32 {
	if m != nil && m.Dihu != nil {
		return *m.Dihu
	}
	return 0
}

func (m *SArchieve) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *SArchieve) GetHutype() uint32 {
	if m != nil && m.Hutype != nil {
		return *m.Hutype
	}
	return 0
}

func (m *SArchieve) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SArchieve_Error
}

// 获取玩家的数据
type CUserData struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1020" json:"code,omitempty"`
	Userid           *string `protobuf:"bytes,2,req,name=userid" json:"userid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CUserData) Reset()         { *m = CUserData{} }
func (m *CUserData) String() string { return proto.CompactTextString(m) }
func (*CUserData) ProtoMessage()    {}

const Default_CUserData_Code uint32 = 1020

func (m *CUserData) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CUserData_Code
}

func (m *CUserData) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

type SUserData struct {
	Code             *uint32   `protobuf:"varint,1,opt,name=code,def=1020" json:"code,omitempty"`
	Data             *UserData `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	Error            *uint32   `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SUserData) Reset()         { *m = SUserData{} }
func (m *SUserData) String() string { return proto.CompactTextString(m) }
func (*SUserData) ProtoMessage()    {}

const Default_SUserData_Code uint32 = 1020
const Default_SUserData_Error uint32 = 0

func (m *SUserData) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SUserData_Code
}

func (m *SUserData) GetData() *UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SUserData) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SUserData_Error
}

// 防沉迷限制
type SChenmi struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=1021" json:"code,omitempty"`
	Coin             *int32  `protobuf:"varint,2,opt,name=coin" json:"coin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SChenmi) Reset()         { *m = SChenmi{} }
func (m *SChenmi) String() string { return proto.CompactTextString(m) }
func (*SChenmi) ProtoMessage()    {}

const Default_SChenmi_Code uint32 = 1021

func (m *SChenmi) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SChenmi_Code
}

func (m *SChenmi) GetCoin() int32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func init() {
}
