// Code generated by protoc-gen-go.
// source: vo.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 客户端登录时提交到逻辑服的玩家信息
type LoginData struct {
	Userid           *string `protobuf:"bytes,1,req,name=userid" json:"userid,omitempty"`
	Nickname         *string `protobuf:"bytes,2,req,name=nickname" json:"nickname,omitempty"`
	Sex              *uint32 `protobuf:"varint,3,req,name=sex" json:"sex,omitempty"`
	Photo            *string `protobuf:"bytes,4,req,name=photo" json:"photo,omitempty"`
	Roomcard         *uint32 `protobuf:"varint,5,req,name=roomcard" json:"roomcard,omitempty"`
	Parent           *string `protobuf:"bytes,6,req,name=parent" json:"parent,omitempty"`
	Timestamp        *uint32 `protobuf:"varint,7,req,name=timestamp" json:"timestamp,omitempty"`
	Token            *string `protobuf:"bytes,8,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginData) Reset()         { *m = LoginData{} }
func (m *LoginData) String() string { return proto.CompactTextString(m) }
func (*LoginData) ProtoMessage()    {}

func (m *LoginData) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *LoginData) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *LoginData) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *LoginData) GetPhoto() string {
	if m != nil && m.Photo != nil {
		return *m.Photo
	}
	return ""
}

func (m *LoginData) GetRoomcard() uint32 {
	if m != nil && m.Roomcard != nil {
		return *m.Roomcard
	}
	return 0
}

func (m *LoginData) GetParent() string {
	if m != nil && m.Parent != nil {
		return *m.Parent
	}
	return ""
}

func (m *LoginData) GetTimestamp() uint32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *LoginData) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// 玩家的详细数据
type UserData struct {
	Userid           *string `protobuf:"bytes,1,req,name=userid" json:"userid,omitempty"`
	Nickname         *string `protobuf:"bytes,2,req,name=nickname" json:"nickname,omitempty"`
	Email            *string `protobuf:"bytes,3,req,name=email" json:"email,omitempty"`
	Phone            *string `protobuf:"bytes,4,req,name=phone" json:"phone,omitempty"`
	Sex              *uint32 `protobuf:"varint,5,req,name=sex" json:"sex,omitempty"`
	Status           *uint32 `protobuf:"varint,6,req,name=status" json:"status,omitempty"`
	Online           *bool   `protobuf:"varint,7,req,name=online" json:"online,omitempty"`
	Exp              *uint32 `protobuf:"varint,8,req,name=exp" json:"exp,omitempty"`
	Ip               *uint32 `protobuf:"varint,9,req,name=ip" json:"ip,omitempty"`
	Photo            *string `protobuf:"bytes,10,req,name=photo" json:"photo,omitempty"`
	Address          *string `protobuf:"bytes,11,req,name=address" json:"address,omitempty"`
	Createtime       *uint32 `protobuf:"varint,12,req,name=createtime" json:"createtime,omitempty"`
	Sign             *string `protobuf:"bytes,13,req,name=sign" json:"sign,omitempty"`
	Birth            *uint32 `protobuf:"varint,14,req,name=birth" json:"birth,omitempty"`
	Terminal         *string `protobuf:"bytes,15,req,name=terminal" json:"terminal,omitempty"`
	Coin             *uint32 `protobuf:"varint,16,req,name=coin" json:"coin,omitempty"`
	Roomtype         *uint32 `protobuf:"varint,18,req,name=roomtype" json:"roomtype,omitempty"`
	Roomid           *uint32 `protobuf:"varint,19,req,name=roomid" json:"roomid,omitempty"`
	Invitecode       *string `protobuf:"bytes,20,req,name=invitecode" json:"invitecode,omitempty"`
	Diamond          *uint32 `protobuf:"varint,21,req,name=diamond" json:"diamond,omitempty"`
	Exchange         *uint32 `protobuf:"varint,22,req,name=exchange" json:"exchange,omitempty"`
	Ticket           *uint32 `protobuf:"varint,23,req,name=ticket" json:"ticket,omitempty"`
	Vip              *uint32 `protobuf:"varint,24,req,name=vip" json:"vip,omitempty"`
	Win              *uint32 `protobuf:"varint,25,req,name=win" json:"win,omitempty"`
	Lost             *uint32 `protobuf:"varint,26,req,name=lost" json:"lost,omitempty"`
	Ping             *uint32 `protobuf:"varint,27,req,name=ping" json:"ping,omitempty"`
	Platform         *uint32 `protobuf:"varint,28,req,name=platform" json:"platform,omitempty"`
	Rupt             *uint32 `protobuf:"varint,29,req,name=rupt" json:"rupt,omitempty"`
	Sound            *bool   `protobuf:"varint,30,req,name=sound" json:"sound,omitempty"`
	Roomcard         *uint32 `protobuf:"varint,31,req,name=roomcard" json:"roomcard,omitempty"`
	Build            *string `protobuf:"bytes,32,req,name=build" json:"build,omitempty"`
	Token            *string `protobuf:"bytes,33,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}

func (m *UserData) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *UserData) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *UserData) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *UserData) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *UserData) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *UserData) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *UserData) GetOnline() bool {
	if m != nil && m.Online != nil {
		return *m.Online
	}
	return false
}

func (m *UserData) GetExp() uint32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *UserData) GetIp() uint32 {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return 0
}

func (m *UserData) GetPhoto() string {
	if m != nil && m.Photo != nil {
		return *m.Photo
	}
	return ""
}

func (m *UserData) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *UserData) GetCreatetime() uint32 {
	if m != nil && m.Createtime != nil {
		return *m.Createtime
	}
	return 0
}

func (m *UserData) GetSign() string {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return ""
}

func (m *UserData) GetBirth() uint32 {
	if m != nil && m.Birth != nil {
		return *m.Birth
	}
	return 0
}

func (m *UserData) GetTerminal() string {
	if m != nil && m.Terminal != nil {
		return *m.Terminal
	}
	return ""
}

func (m *UserData) GetCoin() uint32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *UserData) GetRoomtype() uint32 {
	if m != nil && m.Roomtype != nil {
		return *m.Roomtype
	}
	return 0
}

func (m *UserData) GetRoomid() uint32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *UserData) GetInvitecode() string {
	if m != nil && m.Invitecode != nil {
		return *m.Invitecode
	}
	return ""
}

func (m *UserData) GetDiamond() uint32 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

func (m *UserData) GetExchange() uint32 {
	if m != nil && m.Exchange != nil {
		return *m.Exchange
	}
	return 0
}

func (m *UserData) GetTicket() uint32 {
	if m != nil && m.Ticket != nil {
		return *m.Ticket
	}
	return 0
}

func (m *UserData) GetVip() uint32 {
	if m != nil && m.Vip != nil {
		return *m.Vip
	}
	return 0
}

func (m *UserData) GetWin() uint32 {
	if m != nil && m.Win != nil {
		return *m.Win
	}
	return 0
}

func (m *UserData) GetLost() uint32 {
	if m != nil && m.Lost != nil {
		return *m.Lost
	}
	return 0
}

func (m *UserData) GetPing() uint32 {
	if m != nil && m.Ping != nil {
		return *m.Ping
	}
	return 0
}

func (m *UserData) GetPlatform() uint32 {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return 0
}

func (m *UserData) GetRupt() uint32 {
	if m != nil && m.Rupt != nil {
		return *m.Rupt
	}
	return 0
}

func (m *UserData) GetSound() bool {
	if m != nil && m.Sound != nil {
		return *m.Sound
	}
	return false
}

func (m *UserData) GetRoomcard() uint32 {
	if m != nil && m.Roomcard != nil {
		return *m.Roomcard
	}
	return 0
}

func (m *UserData) GetBuild() string {
	if m != nil && m.Build != nil {
		return *m.Build
	}
	return ""
}

func (m *UserData) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

//  玩家的基础数据
type ProtoUser struct {
	Userid           *string `protobuf:"bytes,1,req,name=userid" json:"userid,omitempty"`
	Nickname         *string `protobuf:"bytes,2,req,name=nickname" json:"nickname,omitempty"`
	Email            *string `protobuf:"bytes,3,req,name=email" json:"email,omitempty"`
	Position         *uint32 `protobuf:"varint,4,req,name=position" json:"position,omitempty"`
	Sex              *uint32 `protobuf:"varint,5,req,name=sex" json:"sex,omitempty"`
	Exp              *uint32 `protobuf:"varint,6,req,name=exp" json:"exp,omitempty"`
	Photo            *string `protobuf:"bytes,7,req,name=photo" json:"photo,omitempty"`
	Address          *string `protobuf:"bytes,8,req,name=address" json:"address,omitempty"`
	Sign             *string `protobuf:"bytes,9,req,name=sign" json:"sign,omitempty"`
	Terminal         *string `protobuf:"bytes,10,req,name=terminal" json:"terminal,omitempty"`
	Coin             *uint32 `protobuf:"varint,11,req,name=coin" json:"coin,omitempty"`
	Roomcard         *uint32 `protobuf:"varint,12,req,name=roomcard" json:"roomcard,omitempty"`
	Exchange         *uint32 `protobuf:"varint,13,req,name=exchange" json:"exchange,omitempty"`
	Ready            *bool   `protobuf:"varint,14,req,name=ready" json:"ready,omitempty"`
	Vip              *uint32 `protobuf:"varint,15,req,name=vip" json:"vip,omitempty"`
	Win              *uint32 `protobuf:"varint,16,req,name=win" json:"win,omitempty"`
	Lost             *uint32 `protobuf:"varint,17,req,name=lost" json:"lost,omitempty"`
	Ping             *uint32 `protobuf:"varint,18,req,name=ping" json:"ping,omitempty"`
	Ting             *uint32 `protobuf:"varint,19,req,name=ting" json:"ting,omitempty"`
	Platform         *uint32 `protobuf:"varint,20,req,name=platform" json:"platform,omitempty"`
	Score            *int32  `protobuf:"varint,21,req,name=score" json:"score,omitempty"`
	Maizi            *int32  `protobuf:"varint,22,req,name=maizi" json:"maizi,omitempty"`
	Ip               *string `protobuf:"bytes,23,req,name=ip" json:"ip,omitempty"`
	Offline          *bool   `protobuf:"varint,24,req,name=offline" json:"offline,omitempty"`
	Longitude        *string `protobuf:"bytes,26,req,name=longitude" json:"longitude,omitempty"`
	Latitude         *string `protobuf:"bytes,27,req,name=latitude" json:"latitude,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoUser) Reset()         { *m = ProtoUser{} }
func (m *ProtoUser) String() string { return proto.CompactTextString(m) }
func (*ProtoUser) ProtoMessage()    {}

func (m *ProtoUser) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *ProtoUser) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *ProtoUser) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *ProtoUser) GetPosition() uint32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *ProtoUser) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *ProtoUser) GetExp() uint32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *ProtoUser) GetPhoto() string {
	if m != nil && m.Photo != nil {
		return *m.Photo
	}
	return ""
}

func (m *ProtoUser) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *ProtoUser) GetSign() string {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return ""
}

func (m *ProtoUser) GetTerminal() string {
	if m != nil && m.Terminal != nil {
		return *m.Terminal
	}
	return ""
}

func (m *ProtoUser) GetCoin() uint32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *ProtoUser) GetRoomcard() uint32 {
	if m != nil && m.Roomcard != nil {
		return *m.Roomcard
	}
	return 0
}

func (m *ProtoUser) GetExchange() uint32 {
	if m != nil && m.Exchange != nil {
		return *m.Exchange
	}
	return 0
}

func (m *ProtoUser) GetReady() bool {
	if m != nil && m.Ready != nil {
		return *m.Ready
	}
	return false
}

func (m *ProtoUser) GetVip() uint32 {
	if m != nil && m.Vip != nil {
		return *m.Vip
	}
	return 0
}

func (m *ProtoUser) GetWin() uint32 {
	if m != nil && m.Win != nil {
		return *m.Win
	}
	return 0
}

func (m *ProtoUser) GetLost() uint32 {
	if m != nil && m.Lost != nil {
		return *m.Lost
	}
	return 0
}

func (m *ProtoUser) GetPing() uint32 {
	if m != nil && m.Ping != nil {
		return *m.Ping
	}
	return 0
}

func (m *ProtoUser) GetTing() uint32 {
	if m != nil && m.Ting != nil {
		return *m.Ting
	}
	return 0
}

func (m *ProtoUser) GetPlatform() uint32 {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return 0
}

func (m *ProtoUser) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *ProtoUser) GetMaizi() int32 {
	if m != nil && m.Maizi != nil {
		return *m.Maizi
	}
	return 0
}

func (m *ProtoUser) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *ProtoUser) GetOffline() bool {
	if m != nil && m.Offline != nil {
		return *m.Offline
	}
	return false
}

func (m *ProtoUser) GetLongitude() string {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return ""
}

func (m *ProtoUser) GetLatitude() string {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return ""
}

// 房间数据(后面要和ProtoRoom合并)
type RoomAttrube struct {
	Rtype            *uint32 `protobuf:"varint,1,req,name=rtype" json:"rtype,omitempty"`
	Ante             *uint32 `protobuf:"varint,2,req,name=ante" json:"ante,omitempty"`
	Maxcount         *uint32 `protobuf:"varint,3,req,name=maxcount" json:"maxcount,omitempty"`
	Percent          *uint32 `protobuf:"varint,4,req,name=percent" json:"percent,omitempty"`
	Access           *uint32 `protobuf:"varint,5,req,name=access" json:"access,omitempty"`
	Private          *uint32 `protobuf:"varint,6,req,name=private" json:"private,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoomAttrube) Reset()         { *m = RoomAttrube{} }
func (m *RoomAttrube) String() string { return proto.CompactTextString(m) }
func (*RoomAttrube) ProtoMessage()    {}

func (m *RoomAttrube) GetRtype() uint32 {
	if m != nil && m.Rtype != nil {
		return *m.Rtype
	}
	return 0
}

func (m *RoomAttrube) GetAnte() uint32 {
	if m != nil && m.Ante != nil {
		return *m.Ante
	}
	return 0
}

func (m *RoomAttrube) GetMaxcount() uint32 {
	if m != nil && m.Maxcount != nil {
		return *m.Maxcount
	}
	return 0
}

func (m *RoomAttrube) GetPercent() uint32 {
	if m != nil && m.Percent != nil {
		return *m.Percent
	}
	return 0
}

func (m *RoomAttrube) GetAccess() uint32 {
	if m != nil && m.Access != nil {
		return *m.Access
	}
	return 0
}

func (m *RoomAttrube) GetPrivate() uint32 {
	if m != nil && m.Private != nil {
		return *m.Private
	}
	return 0
}

type RoomData struct {
	Roomid           *uint32 `protobuf:"varint,1,req,name=roomid" json:"roomid,omitempty"`
	Rtype            *uint32 `protobuf:"varint,2,req,name=rtype" json:"rtype,omitempty"`
	Rname            *string `protobuf:"bytes,3,req,name=rname" json:"rname,omitempty"`
	Expire           *uint32 `protobuf:"varint,4,req,name=expire" json:"expire,omitempty"`
	Count            *uint32 `protobuf:"varint,5,req,name=count" json:"count,omitempty"`
	Cid              *uint32 `protobuf:"varint,6,req,name=cid" json:"cid,omitempty"`
	Invitecode       *string `protobuf:"bytes,7,req,name=invitecode" json:"invitecode,omitempty"`
	Audience         *uint32 `protobuf:"varint,8,req,name=audience" json:"audience,omitempty"`
	Pub              *uint32 `protobuf:"varint,9,req,name=pub" json:"pub,omitempty"`
	Maizi            *bool   `protobuf:"varint,10,req,name=maizi" json:"maizi,omitempty"`
	Horse            *uint32 `protobuf:"varint,11,req,name=horse" json:"horse,omitempty"`
	Zhuang           *uint32 `protobuf:"varint,12,req,name=zhuang" json:"zhuang,omitempty"`
	Round            *uint32 `protobuf:"varint,13,req,name=round" json:"round,omitempty"`
	Userid           *string `protobuf:"bytes,14,req,name=userid" json:"userid,omitempty"`
	Ma               *uint32 `protobuf:"varint,15,req,name=ma" json:"ma,omitempty"`
	Lian             *uint32 `protobuf:"varint,16,req,name=lian" json:"lian,omitempty"`
	Totalround       *uint32 `protobuf:"varint,17,req,name=totalround" json:"totalround,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoomData) Reset()         { *m = RoomData{} }
func (m *RoomData) String() string { return proto.CompactTextString(m) }
func (*RoomData) ProtoMessage()    {}

func (m *RoomData) GetRoomid() uint32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *RoomData) GetRtype() uint32 {
	if m != nil && m.Rtype != nil {
		return *m.Rtype
	}
	return 0
}

func (m *RoomData) GetRname() string {
	if m != nil && m.Rname != nil {
		return *m.Rname
	}
	return ""
}

func (m *RoomData) GetExpire() uint32 {
	if m != nil && m.Expire != nil {
		return *m.Expire
	}
	return 0
}

func (m *RoomData) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *RoomData) GetCid() uint32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *RoomData) GetInvitecode() string {
	if m != nil && m.Invitecode != nil {
		return *m.Invitecode
	}
	return ""
}

func (m *RoomData) GetAudience() uint32 {
	if m != nil && m.Audience != nil {
		return *m.Audience
	}
	return 0
}

func (m *RoomData) GetPub() uint32 {
	if m != nil && m.Pub != nil {
		return *m.Pub
	}
	return 0
}

func (m *RoomData) GetMaizi() bool {
	if m != nil && m.Maizi != nil {
		return *m.Maizi
	}
	return false
}

func (m *RoomData) GetHorse() uint32 {
	if m != nil && m.Horse != nil {
		return *m.Horse
	}
	return 0
}

func (m *RoomData) GetZhuang() uint32 {
	if m != nil && m.Zhuang != nil {
		return *m.Zhuang
	}
	return 0
}

func (m *RoomData) GetRound() uint32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *RoomData) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *RoomData) GetMa() uint32 {
	if m != nil && m.Ma != nil {
		return *m.Ma
	}
	return 0
}

func (m *RoomData) GetLian() uint32 {
	if m != nil && m.Lian != nil {
		return *m.Lian
	}
	return 0
}

func (m *RoomData) GetTotalround() uint32 {
	if m != nil && m.Totalround != nil {
		return *m.Totalround
	}
	return 0
}

// 房间数据结构
type ProtoRoom struct {
	Ante             *uint32 `protobuf:"varint,1,req,name=ante" json:"ante,omitempty"`
	Roomid           *uint32 `protobuf:"varint,2,req,name=roomid" json:"roomid,omitempty"`
	Zhuang           *uint32 `protobuf:"varint,3,req,name=zhuang" json:"zhuang,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoRoom) Reset()         { *m = ProtoRoom{} }
func (m *ProtoRoom) String() string { return proto.CompactTextString(m) }
func (*ProtoRoom) ProtoMessage()    {}

func (m *ProtoRoom) GetAnte() uint32 {
	if m != nil && m.Ante != nil {
		return *m.Ante
	}
	return 0
}

func (m *ProtoRoom) GetRoomid() uint32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *ProtoRoom) GetZhuang() uint32 {
	if m != nil && m.Zhuang != nil {
		return *m.Zhuang
	}
	return 0
}

type PrivateRecordForCircle struct {
	Rid              *uint32 `protobuf:"varint,1,req,name=rid" json:"rid,omitempty"`
	Rname            *string `protobuf:"bytes,2,req,name=rname" json:"rname,omitempty"`
	Time             *uint32 `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	Rtype            *uint32 `protobuf:"varint,4,req,name=rtype" json:"rtype,omitempty"`
	Coin             *int32  `protobuf:"varint,5,req,name=coin" json:"coin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PrivateRecordForCircle) Reset()         { *m = PrivateRecordForCircle{} }
func (m *PrivateRecordForCircle) String() string { return proto.CompactTextString(m) }
func (*PrivateRecordForCircle) ProtoMessage()    {}

func (m *PrivateRecordForCircle) GetRid() uint32 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *PrivateRecordForCircle) GetRname() string {
	if m != nil && m.Rname != nil {
		return *m.Rname
	}
	return ""
}

func (m *PrivateRecordForCircle) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *PrivateRecordForCircle) GetRtype() uint32 {
	if m != nil && m.Rtype != nil {
		return *m.Rtype
	}
	return 0
}

func (m *PrivateRecordForCircle) GetCoin() int32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

type PrivateRecordForRoom struct {
	Uname            *string `protobuf:"bytes,1,req,name=uname" json:"uname,omitempty"`
	Photo            *string `protobuf:"bytes,2,req,name=photo" json:"photo,omitempty"`
	Coin             *int32  `protobuf:"varint,3,req,name=coin" json:"coin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PrivateRecordForRoom) Reset()         { *m = PrivateRecordForRoom{} }
func (m *PrivateRecordForRoom) String() string { return proto.CompactTextString(m) }
func (*PrivateRecordForRoom) ProtoMessage()    {}

func (m *PrivateRecordForRoom) GetUname() string {
	if m != nil && m.Uname != nil {
		return *m.Uname
	}
	return ""
}

func (m *PrivateRecordForRoom) GetPhoto() string {
	if m != nil && m.Photo != nil {
		return *m.Photo
	}
	return ""
}

func (m *PrivateRecordForRoom) GetCoin() int32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

// 明杠  MING_KONG uint32 = 2 << 1
// 暗杠	AN_KONG   uint32 = 2 << 2
// 补杠 	BU_KONG   uint32 = 2 << 3
type ProtoCard struct {
	Peng             []uint32 `protobuf:"varint,1,rep,name=peng" json:"peng,omitempty"`
	Kong             []uint32 `protobuf:"varint,2,rep,name=kong" json:"kong,omitempty"`
	Outcards         []byte   `protobuf:"bytes,3,req,name=outcards" json:"outcards,omitempty"`
	Seat             *uint32  `protobuf:"varint,4,req,name=seat" json:"seat,omitempty"`
	Chow             []uint32 `protobuf:"varint,5,rep,name=chow" json:"chow,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoCard) Reset()         { *m = ProtoCard{} }
func (m *ProtoCard) String() string { return proto.CompactTextString(m) }
func (*ProtoCard) ProtoMessage()    {}

func (m *ProtoCard) GetPeng() []uint32 {
	if m != nil {
		return m.Peng
	}
	return nil
}

func (m *ProtoCard) GetKong() []uint32 {
	if m != nil {
		return m.Kong
	}
	return nil
}

func (m *ProtoCard) GetOutcards() []byte {
	if m != nil {
		return m.Outcards
	}
	return nil
}

func (m *ProtoCard) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *ProtoCard) GetChow() []uint32 {
	if m != nil {
		return m.Chow
	}
	return nil
}

// 结算数据
type ProtoCount struct {
	Seat             *uint32 `protobuf:"varint,1,req,name=seat" json:"seat,omitempty"`
	Cards            []byte  `protobuf:"bytes,2,req,name=cards" json:"cards,omitempty"`
	Hu               *int64  `protobuf:"varint,3,req,name=hu" json:"hu,omitempty"`
	HuTypeFan        *int32  `protobuf:"varint,4,req,name=huTypeFan" json:"huTypeFan,omitempty"`
	HuFan            *int32  `protobuf:"varint,5,req,name=huFan" json:"huFan,omitempty"`
	Maizi            *int32  `protobuf:"varint,7,req,name=maizi" json:"maizi,omitempty"`
	Total            *int32  `protobuf:"varint,8,req,name=total" json:"total,omitempty"`
	Coin             *int32  `protobuf:"varint,9,req,name=coin" json:"coin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoCount) Reset()         { *m = ProtoCount{} }
func (m *ProtoCount) String() string { return proto.CompactTextString(m) }
func (*ProtoCount) ProtoMessage()    {}

func (m *ProtoCount) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *ProtoCount) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *ProtoCount) GetHu() int64 {
	if m != nil && m.Hu != nil {
		return *m.Hu
	}
	return 0
}

func (m *ProtoCount) GetHuTypeFan() int32 {
	if m != nil && m.HuTypeFan != nil {
		return *m.HuTypeFan
	}
	return 0
}

func (m *ProtoCount) GetHuFan() int32 {
	if m != nil && m.HuFan != nil {
		return *m.HuFan
	}
	return 0
}

func (m *ProtoCount) GetMaizi() int32 {
	if m != nil && m.Maizi != nil {
		return *m.Maizi
	}
	return 0
}

func (m *ProtoCount) GetTotal() int32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func (m *ProtoCount) GetCoin() int32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

// 邮箱数据
type PostBoxData struct {
	Title            *string `protobuf:"bytes,1,req,name=title" json:"title,omitempty"`
	Content          *string `protobuf:"bytes,2,req,name=content" json:"content,omitempty"`
	Appendixname     *string `protobuf:"bytes,3,req,name=appendixname" json:"appendixname,omitempty"`
	Expire           *uint32 `protobuf:"varint,4,req,name=expire" json:"expire,omitempty"`
	Sendername       *string `protobuf:"bytes,5,req,name=sendername" json:"sendername,omitempty"`
	Senderuserid     *string `protobuf:"bytes,6,req,name=senderuserid" json:"senderuserid,omitempty"`
	Read             *bool   `protobuf:"varint,7,req,name=read" json:"read,omitempty"`
	Draw             *bool   `protobuf:"varint,8,req,name=draw" json:"draw,omitempty"`
	Kind             *uint32 `protobuf:"varint,9,req,name=kind" json:"kind,omitempty"`
	Id               *uint32 `protobuf:"varint,10,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PostBoxData) Reset()         { *m = PostBoxData{} }
func (m *PostBoxData) String() string { return proto.CompactTextString(m) }
func (*PostBoxData) ProtoMessage()    {}

func (m *PostBoxData) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *PostBoxData) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *PostBoxData) GetAppendixname() string {
	if m != nil && m.Appendixname != nil {
		return *m.Appendixname
	}
	return ""
}

func (m *PostBoxData) GetExpire() uint32 {
	if m != nil && m.Expire != nil {
		return *m.Expire
	}
	return 0
}

func (m *PostBoxData) GetSendername() string {
	if m != nil && m.Sendername != nil {
		return *m.Sendername
	}
	return ""
}

func (m *PostBoxData) GetSenderuserid() string {
	if m != nil && m.Senderuserid != nil {
		return *m.Senderuserid
	}
	return ""
}

func (m *PostBoxData) GetRead() bool {
	if m != nil && m.Read != nil {
		return *m.Read
	}
	return false
}

func (m *PostBoxData) GetDraw() bool {
	if m != nil && m.Draw != nil {
		return *m.Draw
	}
	return false
}

func (m *PostBoxData) GetKind() uint32 {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return 0
}

func (m *PostBoxData) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// 邮箱附件数据
type PostAppendixData struct {
	Postid           *uint32       `protobuf:"varint,1,req,name=postid" json:"postid,omitempty"`
	Name             *string       `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Widgets          []*WidgetData `protobuf:"bytes,3,rep,name=widgets" json:"widgets,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PostAppendixData) Reset()         { *m = PostAppendixData{} }
func (m *PostAppendixData) String() string { return proto.CompactTextString(m) }
func (*PostAppendixData) ProtoMessage()    {}

func (m *PostAppendixData) GetPostid() uint32 {
	if m != nil && m.Postid != nil {
		return *m.Postid
	}
	return 0
}

func (m *PostAppendixData) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PostAppendixData) GetWidgets() []*WidgetData {
	if m != nil {
		return m.Widgets
	}
	return nil
}

// 道具数据
type WidgetData struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Count            *uint32 `protobuf:"varint,2,req,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WidgetData) Reset()         { *m = WidgetData{} }
func (m *WidgetData) String() string { return proto.CompactTextString(m) }
func (*WidgetData) ProtoMessage()    {}

func (m *WidgetData) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *WidgetData) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func init() {
}
